### ISSUE TITLE
Play after long pause state fails

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#766] opened 2019-07-05 17:55 UTC
I'm not sure if this is related to the Pebble play/pause issue, however when I pause music (can be local library files, spotify tracks, etc) and leave it paused for a certain period of time (maybe 30 minutes), then click the play button in the web interface, or an MPD client, playback does not resume.

If I click on pause and fairly shortly after click on play, playback resumes as expected. The issue seems specific to a longer period of being paused.

* I do have the `clear_queue_on_stop_disable = true` setting enabled.

**Comment by ejurgensen** [comment] 2019-07-05 18:01
Can you grab the log (set it to debug level) from when you try to resume playback? Also try to wait 9 and 11 minutes. forked-daapd has a timeout at 10 minutes that might be the cause. When it expires you will see this message in the log: "Timed out after 600 sec without any reading from input source"

**Comment by cdlenfert** [comment] 2019-07-05 20:45
When testing after a 9 minute pause, playback resumed when clicking the play button - [log](https://pastebin.com/3pRd82ry)

When testing after an 11 minute pause, playback failed when clicking the play button - [log](https://pastebin.com/UP94zEP1)

When testing after an 11 minute pause, playbacked succeeded when clicking the "next" button - [log](https://pastebin.com/TPrZ9cqG)

**Comment by ejurgensen** [comment] 2019-07-09 21:17
I've added a fix for this issue, I hope it works. There is still an issue with "mpc pause" + "mpc play" when the source is a radio stream, so I will keep this issue open until I have that fixed as well.

**Comment by ejurgensen** [comment] 2019-07-12 17:34
I've fixed the pausing of the radio streams, plus improved the previous fix, so I am closing this issue.

**Closed by ejurgensen** 2019-07-12 17:34 UTC
Labels: bug

**Comment by cdlenfert** [comment] 2019-07-12 19:32
@ejurgensen does this mean `clear_queue_on_stop_disable = true` is no longer required to pause and resume radio streams? I had to set this in the past or a stream would be removed from my queue when I paused.

**Comment by ejurgensen** [comment] 2019-07-12 21:50
Yes, I think it wouldn't be required any more, but I'm not completely sure, so it would good if you tried it. There has been code that translated radio stream pause to stop, this was to not keep the connection open. That isn't required anymore, but tbh I don't remember if some of the "translation" code is still there, or if it is all gone now.

**Comment by cdlenfert** [comment] 2019-07-16 21:49
@ejurgensen and anyone else who might stumble upon this issue. The `clear_queue_on_stop_disable = true` setting is no longer required to pause/resume streaming radio stations!
