### ISSUE TITLE
Some album artwork displaying as dithered grayscale

### ISSUE THREAD

**Issue by floogs** [ejurgensen/forked-daapd#717] opened 2019-04-07 04:20 UTC
Some of my album art is showing up as a dithered grayscale in the iOS Remote app, connecting to version 26.5 running in a FreeNAS jail (i.e. FreeBSD 11.2).

Most of the album covers in my library show up properly in color, but I can't figure out what's different about the ones that don't (see the pics I attached below). Some affected albums have .jpg covers and others have .png, so it isn't a file type thing. I tried manually adding the art to each album's folder per your naming conventions, but that didn't change anything. (For what it's worth, that did fill in the missing art for albums where forked-daapd wasn't able to see the art embedded in the audio files.)

Any thoughts on a fix, or what I could check to see what's going on here? Thanks for all your work on this project, other than this one minor issue it's working better for me via AirPlay than my genuine iTunes client does.

![IMG_0115](https://user-images.githubusercontent.com/38588287/55677915-bd487000-58a5-11e9-98b9-ef12ff770d7a.JPEG)

![IMG_0405](https://user-images.githubusercontent.com/38588287/55677914-bd487000-58a5-11e9-8271-94cfdaed0fdd.PNG)

![IMG_0116](https://user-images.githubusercontent.com/38588287/55677916-bde10680-58a5-11e9-9dde-e36dafb864e5.PNG)

**Comment by ejurgensen** [comment] 2019-04-07 22:36
That's very peculiar. My guess is that an incorrect pixel format gets used by forked-daapd when it resizes the images. Forked-daapd will ask ffmpeg what the default pixel format is for that encoder (image type), and maybe your version of ffmpeg returns a less than optimal default?

To check for this, you need to:
1. Set the log level to debug in the config
2. Stop forked-daapd
3. Delete the cache.db file (see the location in the config)
4. Restart forked-daapd
5. View the artwork via Remote
6. Check the log for this line: "Pixel format set to xxx (encoder is xxx)" for the relevant images

**Comment by floogs** [comment] 2019-04-08 03:32
Thanks for the response. I pulled a handful of examples from the log that reference albums which are running into this problem (and attached the entire log below if you want it). Maybe worth noting, I used the precompiled ffmpeg from the FreeBSD pkg repository to build forked-daapd, not sure what options it was compiled with originally.

[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/3052495/forked-daapd.log)

I thought it was odd that all three images here seemed to go through different processes (and that monob format on the last one certainly sounds suspect) but all arrived at the same specific result.

```
[2019-04-07 19:58:27] [DEBUG]  artwork: Artwork for 'Dandara's Purpose' found in source 'embedded'
[2019-04-07 19:58:27] [DEBUG]     daap: DAAP request handled in 78 milliseconds
[2019-04-07 19:58:28] [DEBUG]     daap: DAAP request: '/databases/1/groups/221/extra_data/artwork?mw=204&mh=204&group-type=albums&session-id=1079124411'
[2019-04-07 19:58:28] [DEBUG]  artwork: Artwork request for group 221
[2019-04-07 19:58:28] [DEBUG]       db: Running query 'SELECT g.persistentid FROM groups g WHERE g.id = 221;'
[2019-04-07 19:58:28] [DEBUG]    cache: Running query 'SELECT a.format, a.data FROM artwork a WHERE a.type = 0 AND a.persistentid = 3008533415908825386 AND a.max_w = 204 AND a.max_h = 204;'
[2019-04-07 19:58:28] [DEBUG]    cache: No results
[2019-04-07 19:58:28] [DEBUG]       db: Running query 'SELECT g.type FROM groups g WHERE g.persistentid = 3008533415908825386;'
[2019-04-07 19:58:28] [DEBUG]       db: Running query 'SELECT COUNT(DISTINCT(SUBSTR(f.path, 1, LENGTH(f.path) - LENGTH(f.fname) - 1))) FROM files f WHERE f.disabled = 0 AND f.songalbumid = 3008533415908825386;'
[2019-04-07 19:58:28] [DEBUG]       db: Starting query 'SELECT DISTINCT(SUBSTR(f.path, 1, LENGTH(f.path) - LENGTH(f.fname) - 1)) FROM files f WHERE f.disabled = 0 AND f.songalbumid = 3008533415908825386  ;'
[2019-04-07 19:58:28] [DEBUG]       db: End of query results
[2019-04-07 19:58:28] [DEBUG]       db: Running query 'SELECT g.type FROM groups g WHERE g.persistentid = 3008533415908825386;'
[2019-04-07 19:58:28] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND f.songalbumid = 3008533415908825386;'
[2019-04-07 19:58:28] [DEBUG]       db: Starting query 'SELECT f.* FROM files f WHERE f.disabled = 0 AND f.songalbumid = 3008533415908825386  ;'
[2019-04-07 19:58:28] [DEBUG]   ffmpeg: Skipping 0 bytes of junk at 31695.
[2019-04-07 19:58:28] [DEBUG]  artwork: Original image dimensions: w 200 h 178
[2019-04-07 19:58:28] [DEBUG]    xcode: Pixel format set to yuvj444p (encoder is mjpeg)
[2019-04-07 19:58:28] [DEBUG]   ffmpeg: w:200 h:178 pixfmt:yuvj444p tb:1/90000 fr:0/1 sar:100/100 sws_param:
[2019-04-07 19:58:28] [DEBUG]   ffmpeg: w:200 h:178 flags:'bilinear' interl:0
[2019-04-07 19:58:28] [DEBUG]   ffmpeg: w:200 h:178 fmt:yuvj444p sar:100/100 -> w:200 h:178 fmt:yuvj444p sar:1/1 flags:0x2
[2019-04-07 19:58:28] [DEBUG]   ffmpeg: Statistics: 98304 bytes read, 0 seeks
```

```
[2019-04-07 19:57:54] [DEBUG]  artwork: Artwork for 'Moth to a Flame' found in source 'embedded'
[2019-04-07 19:57:54] [DEBUG]     daap: DAAP request handled in 86 milliseconds
[2019-04-07 19:57:54] [DEBUG]     daap: DAAP request: '/databases/1/groups/753/extra_data/artwork?mw=204&mh=204&group-type=albums&session-id=1079124411'
[2019-04-07 19:57:54] [DEBUG]  artwork: Artwork request for group 753
[2019-04-07 19:57:54] [DEBUG]       db: Running query 'SELECT g.persistentid FROM groups g WHERE g.id = 753;'
[2019-04-07 19:57:54] [DEBUG]    cache: Running query 'SELECT a.format, a.data FROM artwork a WHERE a.type = 0 AND a.persistentid = 345807010387596532 AND a.max_w = 204 AND a.max_h = 204;'
[2019-04-07 19:57:54] [DEBUG]    cache: No results
[2019-04-07 19:57:54] [DEBUG]       db: Running query 'SELECT g.type FROM groups g WHERE g.persistentid = 345807010387596532;'
[2019-04-07 19:57:54] [DEBUG]       db: Running query 'SELECT COUNT(DISTINCT(SUBSTR(f.path, 1, LENGTH(f.path) - LENGTH(f.fname) - 1))) FROM files f WHERE f.disabled = 0 AND f.songalbumid = 345807010387596532;'
[2019-04-07 19:57:54] [DEBUG]       db: Starting query 'SELECT DISTINCT(SUBSTR(f.path, 1, LENGTH(f.path) - LENGTH(f.fname) - 1)) FROM files f WHERE f.disabled = 0 AND f.songalbumid = 345807010387596532  ;'
[2019-04-07 19:57:54] [DEBUG]       db: End of query results
[2019-04-07 19:57:54] [DEBUG]       db: Running query 'SELECT g.type FROM groups g WHERE g.persistentid = 345807010387596532;'
[2019-04-07 19:57:54] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND f.songalbumid = 345807010387596532;'
[2019-04-07 19:57:54] [DEBUG]       db: Starting query 'SELECT f.* FROM files f WHERE f.disabled = 0 AND f.songalbumid = 345807010387596532  ;'
[2019-04-07 19:57:54] [DEBUG]   ffmpeg: Skipping 0 bytes of junk at 298.
[2019-04-07 19:57:54] [DEBUG]   ffmpeg: Statistics: 32768 bytes read, 0 seeks
```

```
[2019-04-07 19:57:59] [DEBUG]  artwork: Artwork for 'Bionic Commando Main Theme Rearmed' found in source 'embedded'
[2019-04-07 19:57:59] [DEBUG]     daap: DAAP request handled in 37 milliseconds
[2019-04-07 19:58:00] [DEBUG]     daap: DAAP request: '/databases/1/groups/934/extra_data/artwork?mw=204&mh=204&group-type=albums&session-id=1079124411'
[2019-04-07 19:58:00] [DEBUG]  artwork: Artwork request for group 934
[2019-04-07 19:58:00] [DEBUG]       db: Running query 'SELECT g.persistentid FROM groups g WHERE g.id = 934;'
[2019-04-07 19:58:00] [DEBUG]    cache: Running query 'SELECT a.format, a.data FROM artwork a WHERE a.type = 0 AND a.persistentid = 8350238030023045079 AND a.max_w = 204 AND a.max_h = 204;'
[2019-04-07 19:58:00] [DEBUG]    cache: Cache hit: SELECT a.format, a.data FROM artwork a WHERE a.type = 0 AND a.persistentid = 8350238030023045079 AND a.max_w = 204 AND a.max_h = 204;
[2019-04-07 19:58:00] [DEBUG]  artwork: Source 'cache' stopped search for artwork for group 8350238030023045079
[2019-04-07 19:58:00] [DEBUG]  artwork: No artwork found for group 934
[2019-04-07 19:58:00] [DEBUG]     daap: DAAP request handled in 1 milliseconds
[2019-04-07 19:58:00] [DEBUG]     daap: DAAP request: '/databases/1/groups/259/extra_data/artwork?mw=204&mh=204&group-type=albums&session-id=1079124411'
[2019-04-07 19:58:00] [DEBUG]  artwork: Artwork request for group 259
[2019-04-07 19:58:00] [DEBUG]       db: Running query 'SELECT g.persistentid FROM groups g WHERE g.id = 259;'
[2019-04-07 19:58:00] [DEBUG]    cache: Running query 'SELECT a.format, a.data FROM artwork a WHERE a.type = 0 AND a.persistentid = 2539830736546615439 AND a.max_w = 204 AND a.max_h = 204;'
[2019-04-07 19:58:00] [DEBUG]    cache: No results
[2019-04-07 19:58:00] [DEBUG]       db: Running query 'SELECT g.type FROM groups g WHERE g.persistentid = 2539830736546615439;'
[2019-04-07 19:58:00] [DEBUG]       db: Running query 'SELECT COUNT(DISTINCT(SUBSTR(f.path, 1, LENGTH(f.path) - LENGTH(f.fname) - 1))) FROM files f WHERE f.disabled = 0 AND f.songalbumid = 2539830736546615439;'
[2019-04-07 19:58:00] [DEBUG]       db: Starting query 'SELECT DISTINCT(SUBSTR(f.path, 1, LENGTH(f.path) - LENGTH(f.fname) - 1)) FROM files f WHERE f.disabled = 0 AND f.songalbumid = 2539830736546615439  ;'
[2019-04-07 19:58:00] [DEBUG]       db: End of query results
[2019-04-07 19:58:00] [DEBUG]       db: Running query 'SELECT g.type FROM groups g WHERE g.persistentid = 2539830736546615439;'
[2019-04-07 19:58:00] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND f.songalbumid = 2539830736546615439;'
[2019-04-07 19:58:00] [DEBUG]       db: Starting query 'SELECT f.* FROM files f WHERE f.disabled = 0 AND f.songalbumid = 2539830736546615439  ;'
[2019-04-07 19:58:00] [DEBUG]   ffmpeg: Skipping 0 bytes of junk at 1543416.
[2019-04-07 19:58:00] [ WARN]   ffmpeg: Estimating duration from bitrate, this may be inaccurate
[2019-04-07 19:58:00] [DEBUG]  artwork: Original image dimensions: w 1021 h 1021
[2019-04-07 19:58:00] [DEBUG]  artwork: Rescale required, destination width 204 height 204
[2019-04-07 19:58:00] [DEBUG]    xcode: Pixel format set to monob (encoder is png)
[2019-04-07 19:58:00] [DEBUG]   ffmpeg: w:1021 h:1021 pixfmt:rgb24 tb:1/90000 fr:0/1 sar:2835/2835 sws_param:
[2019-04-07 19:58:00] [DEBUG]   ffmpeg: w:204 h:204 flags:'bilinear' interl:0
[2019-04-07 19:58:00] [DEBUG]   ffmpeg: w:iw h:ih flags:'bilinear' interl:0
[2019-04-07 19:58:00] [DEBUG]   ffmpeg: auto-inserting filter 'auto_scaler_0' between the filter 'in' and the filter 'format'
[2019-04-07 19:58:00] [ WARN]   ffmpeg: full chroma interpolation for destination format 'monob' not yet implemented
[2019-04-07 19:58:00] [DEBUG]   ffmpeg: w:1021 h:1021 fmt:rgb24 sar:2835/2835 -> w:1021 h:1021 fmt:monob sar:1/1 flags:0x2
[2019-04-07 19:58:00] [ WARN]   ffmpeg: full chroma interpolation for destination format 'monob' not yet implemented
[2019-04-07 19:58:00] [DEBUG]   ffmpeg: w:1021 h:1021 fmt:monob sar:1/1 -> w:204 h:204 fmt:monob sar:1/1 flags:0x2
[2019-04-07 19:58:00] [DEBUG]   ffmpeg: Statistics: 1598650 bytes read, 0 seeks
```

**Comment by ejurgensen** [comment] 2019-04-08 10:26
So all three examples are showing up in dithered monochrome? That is indeed odd.

To progress with the issue I would need to reproduce it. Can you check what version of ffmpeg you are using? And can you send me an affected track (espenjurgensen@gmail.com)?

**Comment by ejurgensen** [comment] 2019-04-08 19:15
That ffmpeg version 4.1.3 is just 7 days old, so you are pretty up to date!

I had a look at the log and the files, and I can see the issue is actually the same (see below). In all three cases "monob" is chosen as pixel format for png, which is wrong. The cause of this is that ffmpeg has changed the behavior of avcodec_default_get_format(), which forked-daapd uses. Before it would return the first element in the list of supported encoder pixel formats (for png rgb24), but now it returns the last (monob). I don't understand why they have made that change, but it seems to be on purpose. This change will also affect jpg, so that's probably the reason you see it there too.

The only fix I can think of is to stop using avcodec_default_get_format() and instead hardcoding the pixel formats. So I will probably make that change in a few days.

```
[2019-04-07 19:58:27] [DEBUG]    xcode: Pixel format set to monob (encoder is png)
[2019-04-07 19:58:27] [DEBUG]   ffmpeg: w:800 h:800 pixfmt:rgb24 tb:1/90000 fr:0/1 sar:2835/2835 sws_param:
[2019-04-07 19:58:27] [DEBUG]   ffmpeg: w:204 h:204 flags:'bilinear' interl:0
[2019-04-07 19:58:27] [DEBUG]   ffmpeg: w:iw h:ih flags:'bilinear' interl:0
[2019-04-07 19:58:27] [DEBUG]   ffmpeg: auto-inserting filter 'auto_scaler_0' between the filter 'in' and the filter 'format'
[2019-04-07 19:58:27] [ WARN]   ffmpeg: full chroma interpolation for destination format 'monob' not yet implemented
[2019-04-07 19:58:27] [DEBUG]   ffmpeg: w:800 h:800 fmt:rgb24 sar:2835/2835 -> w:800 h:800 fmt:monob sar:1/1 flags:0x2
[2019-04-07 19:58:27] [ WARN]   ffmpeg: full chroma interpolation for destination format 'monob' not yet implemented
[2019-04-07 19:58:27] [DEBUG]   ffmpeg: w:800 h:800 fmt:monob sar:1/1 -> w:204 h:204 fmt:monob sar:1/1 flags:0x2
[2019-04-07 19:58:27] [DEBUG]   ffmpeg: Statistics: 1465069 bytes read, 0 seeks
[2019-04-07 19:58:27] [DEBUG]  artwork: Artwork for 'Dandara's Purpose' found in source 'embedded'

[2019-04-07 19:57:54] [DEBUG]    xcode: Pixel format set to monob (encoder is png)
[2019-04-07 19:57:54] [DEBUG]   ffmpeg: w:800 h:800 pixfmt:rgba tb:1/90000 fr:0/1 sar:2834/2834 sws_param:
[2019-04-07 19:57:54] [DEBUG]   ffmpeg: w:204 h:204 flags:'bilinear' interl:0
[2019-04-07 19:57:54] [DEBUG]   ffmpeg: w:iw h:ih flags:'bilinear' interl:0
[2019-04-07 19:57:54] [DEBUG]   ffmpeg: auto-inserting filter 'auto_scaler_0' between the filter 'in' and the filter 'format'
[2019-04-07 19:57:54] [ WARN]   ffmpeg: full chroma interpolation for destination format 'monob' not yet implemented
[2019-04-07 19:57:54] [DEBUG]   ffmpeg: w:800 h:800 fmt:rgba sar:2834/2834 -> w:800 h:800 fmt:monob sar:1/1 flags:0x2
[2019-04-07 19:57:54] [ WARN]   ffmpeg: full chroma interpolation for destination format 'monob' not yet implemented
[2019-04-07 19:57:54] [DEBUG]   ffmpeg: w:800 h:800 fmt:monob sar:1/1 -> w:204 h:204 fmt:monob sar:1/1 flags:0x2
[2019-04-07 19:57:54] [DEBUG]   ffmpeg: Statistics: 479940 bytes read, 0 seeks
[2019-04-07 19:57:54] [DEBUG]  artwork: Artwork for 'Moth to a Flame' found in source 'embedded'

[2019-04-07 19:57:59] [DEBUG]    xcode: Pixel format set to monob (encoder is png)
[2019-04-07 19:57:59] [DEBUG]   ffmpeg: w:300 h:300 pixfmt:rgb24 tb:1/90000 fr:0/1 sar:2835/2835 sws_param:
[2019-04-07 19:57:59] [DEBUG]   ffmpeg: w:204 h:204 flags:'bilinear' interl:0
[2019-04-07 19:57:59] [DEBUG]   ffmpeg: w:iw h:ih flags:'bilinear' interl:0
[2019-04-07 19:57:59] [DEBUG]   ffmpeg: auto-inserting filter 'auto_scaler_0' between the filter 'in' and the filter 'format'
[2019-04-07 19:57:59] [ WARN]   ffmpeg: full chroma interpolation for destination format 'monob' not yet implemented
[2019-04-07 19:57:59] [DEBUG]   ffmpeg: w:300 h:300 fmt:rgb24 sar:2835/2835 -> w:300 h:300 fmt:monob sar:1/1 flags:0x2
[2019-04-07 19:57:59] [ WARN]   ffmpeg: full chroma interpolation for destination format 'monob' not yet implemented
[2019-04-07 19:57:59] [DEBUG]   ffmpeg: w:300 h:300 fmt:monob sar:1/1 -> w:204 h:204 fmt:monob sar:1/1 flags:0x2
[2019-04-07 19:57:59] [DEBUG]   ffmpeg: Statistics: 262144 bytes read, 0 seeks
[2019-04-07 19:57:59] [DEBUG]  artwork: Artwork for 'Bionic Commando Main Theme Rearmed' found in source 'embedded'
```

**Comment by floogs** [comment] 2019-04-12 21:01
I got a chance to grab the updated master branch and rebuild with this fix, and it worked like a charm. All the previously monochrome images look correct now -- thanks for the quick fix.

I do also have quite a few albums that forked-daapd wasn't able to find the embedded artwork in, even though iTunes and VLC are able to see it. At a glance, the music files in this case generally seem to be at least a decade old, so maybe the cover images were applied using some kind of obsolete embedding scheme that's no longer widely recognized? This is more of an annoyance than a real issue since it works to just extract the cover image and add it manually to the album folder, but thought I'd mention it as well in case it's of interest.

**Comment by whatdoineed2do** [comment] 2019-04-13 15:01
It's likely that itunes is using the metadata from your mp3s and grabbing cover art behind the scenes.

For those albums/files that `forked-daap` doesn't show cover art, you can run `ffprobe -i foo.mp3`and verify what's actually in the meta.

eg: look for a `png` or `jpeg` stream like this file:
```
$ fprobe -hide_banner -i art/test.mp3 
Input #0, mp3, from 'art/test.mp3':
  Metadata:
    artist          : Marvin Gaye
    title           : Lets Get It On
    genre           : Pop
    comment         : id3v2 comment
    encoder         : Lavf57.71.100
    track           : 2
    album           : Greatest Hits
    date            : 1977
  Duration: 00:00:03.63, start: 0.025056, bitrate: 817 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : LAME3.96r
    Side data:
      replaygain: track gain - -9.400000, track peak - unknown, album gain - unknown, album peak - unknown, 
    Stream #0:1: Video: png, rgb24(pc), 800x640 [SAR 2834:2834 DAR 5:4], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      title           : Album cover
      comment         : Cover (front)
```

**Comment by ejurgensen** [comment] 2019-04-15 09:38
Good to hear the fix worked, closing the issue then

**Closed by ejurgensen** 2019-04-15 09:38 UTC
Labels: bug
