### ISSUE TITLE
Album art mixup with macOS app Music 1.0.6.10

### ISSUE THREAD

**Issue by maichai** [ejurgensen/forked-daapd#1187] opened 2021-02-07 21:53 UTC
forked-daapd 27.2 compiled with support for ffmpeg, iTunes XML, Spotify, LastFM, Chromecast, MPD, Device verification, Websockets, ALSA, Webinterface. Running as a container `linuxserver/daapd`latest

macOS app Music 1.0.6.10 on Catalina 10.15.7

Things that are working:
- RAOP streaming from forked-daapd to AirPlay capable devices such as Kodi and an AVR
- DACP controlling forked-daapd using iOS app Remote
- DAAP accessing forked-daapd library using macOS app Music

Problem:
- initially all album art was properly shown
- when accessing the forked-daap library using the macOS app Music, the album art may be assigned wrongly, i.e. album art of titles available in the library are shown for different titles available in the library
- this happened after some testing, and after some other testing the album art was back OK, alas, I cannot describe reproducible steps for this
- however the album art is always shown properly assigned within the iOS app Remote and in the forked-daapd web UI
- album art embedded in the audio files are proper, as verified with other tools

Things I already tried to mitigate the problem, but they did not help:
- remove all db and cache files and restart the container
- update the forked-daapd database and the metadata
- clear the cache of the Music app under settings > advanced > Reset Music store cache
- reboot macOS

**Comment by ejurgensen** [comment] 2021-02-08 10:46
Thanks for notifying about this, but it is hard to do anything about it due to the lack of reproducability and/or debug logging. So I think I will have to close the issue.

**Closed by ejurgensen** 2021-02-08 10:46 UTC

**Comment by maichai** [comment] 2021-02-12 22:44
Even if you think that is not a bug in forked-daapd I think this is the right place to get this problem analyzed and solved in the community, as the problem does not occur with the local library of the Music app. The only people who would see the same problem would be forked-daapd users. I posed this again as a question, please do not close that as I do not expect you as the author to respond, but some users who had the same problem.

**Comment by ejurgensen** [comment] 2021-02-15 09:19
Ok, let's see if anyone has any input on the matter. I would like to avoid having too many stale issues, so please close it if there is no response after a month or so.
