### ISSUE TITLE
db query unknown type 4

### ISSUE THREAD

**Issue by grogcw** [ejurgensen/forked-daapd#505] opened 2018-03-08 18:53 UTC
Hi !

After installing and starting, everything works nice and smooth, but I discovered a wild bug after connecting "Remote for iTunes" android app.

While browsing the server's collection, the app can't load the songs inside any albums (but a workaround for playing I found is holding album item and -> "play album" seems to work fine) while the server log outputs on every query :

[2018-03-08 19:47:34] [  LOG]       db: Could not create query, unknown type 4
[2018-03-08 19:47:34] [  LOG]     daap: Could not start query

I don't have any ideas on how the query is built up, I'm not affiliated to the app's creator, so I can't really help there...

Any ideas ?

**Comment by ejurgensen** [comment] 2018-03-08 21:34
Yes, I see it is asking for playlist 0 which is odd because there is never a playlist 0. I figure I should be able to reproduce this problem, so may I ask precisely what you press in "Remote for iTunes" that produces the error? You mentioned albums, but here it seems you are actually looking at playlists?

**Comment by grogcw** [comment] 2018-03-08 21:40
On every item in the app (Genres, Artists, Albums, Playlists) I tap on, the query seems to output this.

About the playlist bit, actually no, I'm just browsing through albums for sure.

Maybe the application itself crawl and search in the entire db. Strange behavior, but why not...

**Comment by ejurgensen** [comment] 2018-03-08 21:47
Very odd indeed. If it wanted the entire db it could just request playlist 1, that is what iTunes defines as "entire library". Did you try simply disconnecting from the library, force closing the app and then re-connecting?

**Comment by grogcw** [comment] 2018-03-08 21:50
Yes, for sure, I wouldn't have you involved if it was a simple app bug :/

What is playlist 0 in daapd code ?

Can't it be "symlinked" to 1 hence avoiding the bug to occur ?

Sorry for blanket pulling here...

**Comment by ejurgensen** [comment] 2018-03-09 17:50
Sure, I can pretend 0 is really 1. Whether it works, however, depends on what Remote for iTunes is actually trying to get.

I have made the change in the branch https://github.com/ejurgensen/forked-daapd/tree/remote_workaround. Are you able to build and test it? Otherwise let me know, maybe I can help you with a binary.

**Comment by grogcw** [comment] 2018-03-11 14:30
Works like a charm now, first try :)

Compiled successfully on first try with chromecast and libwebsockets.

As predicted, the log shows this :

LOG]     daap: Client 'Dalvik/2.1.0 (Linux; U; Android 5.0; SM-N9005 Build/LRX21V)' made invalid request for playlist 0, returning playlist 1

...and when the app gets this reply, it works instantly.

I still thinks it's on the app side that there's a problem, but, heh, you've got the problem resolved !

[BTW, you can update the iTunes (OSX) version's compliance to 12.7.3]


Thanks for taking care !

Cheers !

**Comment by ejurgensen** [comment] 2018-03-11 21:43
Good to here. I have merged the change into master. Also thank you for mentioning the iTunes version, I have updated that too.

**Closed by ejurgensen** 2018-03-11 21:43 UTC
