### ISSUE TITLE
Minor issue with unexpected behavior with random playlist in Web frontend

### ISSUE THREAD

**Issue by LordMyschkin** [ejurgensen/forked-daapd#1085] opened 2020-08-24 18:16 UTC
I learned to love the smart random playlist feature recently added; but there is a problem with web frontend.
Steps to reproduce:
create a smart playlist with 100 random tracks: "random 100" {
    media_kind is music
    order by random desc
    limit 100
}

select that playlist (--> queue 1), start playing, then (cause you dont like that randon selection)
then select that playlist again (queue 2)

while the frontend still shows queue 1 even when playing queue 2 (the playlist just does not get updated); mpc playlist shows queue 2
When you select the trackinfo and than the playlist view again, the correct playlist (queue 2) gets displayed.

is there a way to update the display after selecting the playlist?

**Comment by whatdoineed2do** [comment] 2020-08-27 08:46
I took a look at this and we can see that the browser is caching the playlist so when you hit the playlist page again, the cached version is shown, whereas we need the page to call back to the server again to get the next set of random tracks.

What i can't quite see is how to force `vuejs` to not cache particular pages like in this instance.  This situation probably applies to the podcast page too.

@chme - have you come across anything that allows you to disable caching/force the remote load of data when visiting a page in the web ui?

**Comment by chme** [comment] 2020-08-29 12:20
Caching is kind of problematic in some places. 

In #1082 I have included a JSON API change (https://github.com/ejurgensen/forked-daapd/pull/1082/commits/0352539f8285ccc36432a79ccc72e7a5ccff2aed) that fixed it in my tests. The problem is the "Cache-Control" header forked-daapd sets. For playlists this was "private no-cache" in combination with "Last-Modified" header. This tells the browser to always check if a cached version can be used. The "Last-Modified" is the timestamp of the last rescan. Thus this did not work for random playlists (forked-daapd tells the browser that the cached version is still valid). The mentioned commit changes this and forked-daapd now sets "Cache-Control" to "no-store", which tells the browser to never cache the response.

**Comment by whatdoineed2do** [comment] 2020-08-29 14:11
great stuff works nicely.

**Comment by whatdoineed2do** [comment] 2020-09-03 16:40
@chme - i just retested the podcasts page when adding a new podcast and the caching behaviour strikes again.

To reproduce:
* goto http://localhost:3689/#/podcasts
* use `Add Podcast` to add a NEW valid podcast
* the `ablums` (ie list of podcasts`) is not updated even though the episodes of new podcast are shown

This is again because of the caching - I can see that once the web ui has completed the RSS subscription, it will hit `jsonapi_reply_library_albums()` again as directed by 

https://github.com/ejurgensen/forked-daapd/blob/70403826889aa5151b7d5447d19565719bc193e4/web-src/src/pages/PagePodcasts.vue#L80-L83

to

https://github.com/ejurgensen/forked-daapd/blob/70403826889aa5151b7d5447d19565719bc193e4/web-src/src/pages/PagePodcasts.vue#L197-L200

However, because of the caching, the json side thinks nothings changed and returns as such so the list of podcasts remains unchangeded.  This could be fixed by calling `httpd_response_not_cachable()` when `media_kinda == MEDIA_KIND_PODCAST`
```
## adding new podcast
[ INFO]     http: Making request for https://itunes.apple.com/lookup?id=1319947289
[ INFO]     http: Making request for https://feeds.pacific-content.com/commandlineheroes
[ WARN]   ffmpeg: Estimating duration from bitrate, this may be inaccurate
[ WARN]   ffmpeg: Estimating duration from bitrate, this may be inaccurate
[ WARN]   ffmpeg: Estimating duration from bitrate, this may be inaccurate
[ WARN]   ffmpeg: Estimating duration from bitrate, this may be inaccurate
[ WARN]   ffmpeg: Estimating duration from bitrate, this may be inaccurate
[ WARN]     scan: ffmpeg/libav could not extract any metadata
[ INFO]     scan: Added or updated 10 items from RSS feed 'https://podcasts.apple.com/au/podcast/command-line-heroes/id1319947289' (id 15)
[  LOG]      web: *** ask for albums -- not modified, returning  ***
```

**Closed** 2020-10-17 06:01 UTC
