### ISSUE TITLE
Docker based version 26 keeps crashing

### ISSUE THREAD

**Issue by sparklyballs** [ejurgensen/forked-daapd#502] opened 2018-03-03 18:26 UTC
Hi there i'm from linuxserver and this week we updated our docker to build version 26 

however when attempting to play anything in itunes the app restarts and drops the connection

the log output such as it is

https://pastebin.com/bNWS6L6K

we use alpine linux for our image but i also built a ubuntu xenial version for test purposes and that does the same as the alpine version and restarts when trying to play anything in itunes

**Comment by sparklyballs** [comment] 2018-03-03 18:39
our Dockerfile 

https://github.com/linuxserver/docker-daapd/blob/master/Dockerfile

and the jenkins build log 

https://ci.linuxserver.io/job/Docker-Builders/job/x86-64/job/x86-64-daapd/134/console

**Comment by ejurgensen** [comment] 2018-03-03 19:23
If there is a problem with the release I will make it a high priority to fix it. The log you doesn't really show anything (there is an mdns error, but it seems unrelated and seems to go away). Could you set the log level to debug in forked-daapd.conf on the Xenial box, retry, and then share it?

**Comment by sparklyballs** [comment] 2018-03-03 20:09
typical lol

before posting it was crashing consistently now you've asked for debug logs can't get it to crash

**Comment by sparklyballs** [comment] 2018-03-03 20:20
damn now even the alpine version is running


believe me though it was constantly crashing and we've had reports from our users experiencing crashing too

**Comment by ejurgensen** [comment] 2018-03-03 22:45
Yes, that is typical :-) Don't worry, I believe you. Since there aren't any clues to go on, I have to resort to some guessing: The crash could perhaps be triggered by the ffmpeg transcoding, in which case it would depend on the file that you start listening to in iTunes. So when it is now not crashing, is it then perhaps because it is another file you are trying to play?

**Comment by ejurgensen** [comment] 2018-03-03 23:41
I tried on a fresh install of Xenial, but could not produce the crash. Tried with a flac and a mp3.

I can, however, say that the mdns errors present in your log are because Avahi isn't running (or ready). But I guess you got that sorted out, since you later seem to be able to start forked-daapd.

**Comment by tmarczin** [comment] 2018-03-04 10:00
Hi All,

I'm one of the people affected by the problem sparklyballs is talking about. I went ahead and reinstalled the latest version and could recreate the issue with debug level logging. I've connected twice to the server to gather some data. The log is pasted here: https://pastebin.com/9GGkjSC3

Tried to include just a few music folders, but please let me know if you find any specific file causing the problem, I'd be glad if I could help somehow.

**Comment by ejurgensen** [comment] 2018-03-04 11:09
Thanks, that is very useful. I can see either forked-daapd or ffmpeg is crashing while handling an iTunes artwork request. It is trying to retrieve artwork from a media file with embedded artwork that is 700x700. It would be great if you could send me the file so I can try to reproduce. You can send it to espenjurgensen@gmail.com.

To find out what file it is you can do the following:
```
sqlite3 /var/cache/forked-daapd/songs3.db (if that is the db location on your machine)
select path from files where id=230;
(you can then exit with .quit)
```

**Comment by sparklyballs** [comment] 2018-03-04 11:15
that would explain why i'm unable to get it to crash again the artwork was likely already there from previous attempts as i was only using a small sample of my music lib

**Comment by tmarczin** [comment] 2018-03-04 11:25
Sorry, restarted the docker with a previous build to listen to some music. But I redid the test. This is the new log, I think I see the part you are talking about.
https://pastebin.com/s44UvUZe

Based on this I've did what you've asked, but with the song ID 4926.
I'll send you the file in a few minutes. It's some "The Haunted" :)

**Comment by TrisMcC** [comment] 2018-03-04 17:05
It crashed for me constantly using the official alpine image. The log message was always some ominous issue with ffmpeg, either related to artwork or streaming, and I couldn't do any mp3 stream longer than 59 seconds.

I rebuilt my own image using a well-known ffmpeg image, which is based on ubuntu.

https://pastebin.com/raw/Lv5Mybnf

The only issue I have now is sometimes iTunes won't move to the next song and popup a "rebuffering" message.

**Comment by tmarczin** [comment] 2018-03-04 17:12
Just a heads up: I reverted to an earlier version of the linixserver.io docker for unRaid that is using version 25 of forked-daapd and I've been able to stream music for hours without issues.

**Comment by ejurgensen** [comment] 2018-03-04 21:17
I made an Alpine Linux VM and with the file from @tmarczin I was able to reproduce the crash. I traced the crash to a ffmpeg call (avcodec_send_frame). Why ffmpeg crashes on that call is not clear to me, but it could well be a bug in ffmpeg 3.4, because I then upgraded ffmpeg to 3.4.2, and that solved the problem.

As you note, the problem will not happen with forked-daapd 25. That is because the old version uses an older ffmpeg API, and thus doesn't use avcodec_send_frame().

So the best solution would be to upgrade your Docker build to use ffmpeg 3.4.2, but that might not be an option for you in the short run. In that case I have added a configure option to forked-daapd, so you can set it to use the old ffmpeg API, thus avoiding the problem. The configure option is "--disable-avcodecsend". See the commit above, if you want to grab it as a patch.

**Comment by sparklyballs** [comment] 2018-03-05 13:18
i rebuilt a test alpine linux image using ffmpeg 3.4.2 and with the log set to debug got this

https://youtu.be/LlLnXUxpiM8


[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/1780917/forked-daapd.log)

**Comment by ejurgensen** [comment] 2018-03-05 19:04
I tried again with my ffmpeg 3.4.2 on Alpine Linux, still no crash. I then tried to build ffmpeg 3.4 from source, installed it, and no crash. So it seems it is not the ffmpeg version that matters, like you also found, but how it gets built. Maybe there is some special build option that needs to be present for the problem to appear.

Since I can only produce the crash with stock ffmpeg, and that was not built with debug information, it is hard to trace the error. Since you are able to build 3.4.2 in a manner that still crashes, perhaps you can tell me how you do?

Another thing you could help with is to try and install valgrind, and then run it forked-daapd with that, i.e. `valgrind /usr/sbin/forked-daapd`

**Comment by ejurgensen** [comment] 2018-03-06 21:40
I now tried building ffmpeg exactly as the Alpine Linux build, i.e. using the same configure options and even the patch documented here: https://git.alpinelinux.org/cgit/aports/tree/main/ffmpeg?h=3.7-stable

But I am clearly still missing the key ingredient, because with this build of ffmpeg there is no crashing.

So I hope you can help me with a recipe for building a ffmpeg that crashes forked-daapd. Without it, I don't think I will be able to do anything about the issue here. I won't rule out that forked-daapd is providing invalid data to ffmpeg, but I can't find out if I can't trace into the ffmpeg libraries.

**Comment by sparklyballs** [comment] 2018-03-06 22:07
i didn't build ffmpeg 3.4.2

i installed it from the edge repo https://pkgs.alpinelinux.org/package/edge/main/x86_64/ffmpeg

**Comment by sparklyballs** [comment] 2018-03-06 22:13
`apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/main ffmpeg`

will you get you that version in alpine VM

**Comment by ejurgensen** [comment] 2018-03-07 09:06
Thanks, but as I wrote I need a crash-prone ffmpeg _with_ debug information, otherwise the only information I get from the debugger is that there was a problem in libavcodec. That doesn't help me much.

That is why I am trying to build a crash-ffmpeg myself. That also would allow me to tinker with the ffmpeg code to see what might be going on.

**Comment by sparklyballs** [comment] 2018-03-07 12:20
is this getting somewhere towards what you want for testing ? 

this builds ffmpeg 3.4.2

https://github.com/linuxserver/docker-daapd/blob/test_build/Dockerfile

key lines being

https://github.com/linuxserver/docker-daapd/blob/test_build/Dockerfile#L96
https://github.com/linuxserver/docker-daapd/blob/test_build/Dockerfile#L123

**Comment by ejurgensen** [comment] 2018-03-07 15:26
Yes, line 123 should to the trick. Line 96 isn't strictly necessary since I can just install Valgrind by myself, I suppose.

So where does this build go, and how would I go about installing it in a VM? If you have a link to some guide it would be good.

**Comment by ejurgensen** [comment] 2018-04-03 19:54
Did you see my last request? I hope you can help install the debug-enabled ffmpeg 3.4.2 Docker, so that I can run it and see what the debugger says. Otherwise I will have to close the issue.

**Comment by sparklyballs** [comment] 2018-04-05 10:12
i missed the last request (lost in a sea of github emails) 

i had assumed you could build from the Dockerfile but failing that i will build it locally and you can pull 

linuxserver/daapd:test from dockerhub

**Comment by sparklyballs** [comment] 2018-04-05 10:31
it's pushed to the hub and you can use it with

`docker run --rm=true -it --entrypoint=bash --net=host linuxserver/daapd:test`


which will you give a shell inside the image 


the app is at `/app/sbin`

**Comment by ejurgensen** [comment] 2018-04-05 11:16
I have no experience at all with Docker, so need to be held in the hand a bit... if you have a link to a good intro please share. Will google for it otherwise.

**Comment by ejurgensen** [comment] 2018-04-05 20:30
I now have the Docker image and can run it. Any hints on how to start avahi? Good old /etc/init.d/avahi-daemon start didn't seem to do the trick. I also tried `rc-service avahi-daemon start`, it just says that the "service is already starting", but it doesn't seem to actually start.

**Comment by ejurgensen** [comment] 2018-04-08 18:54
@sparklyballs any advice on how to start Avahi?

**Comment by jompjomp** [comment] 2018-04-09 23:50
I bumped the daapd thread ejurgensen, hopefully he’ll see it. 

https://lime-technology.com/forums/topic/42513-support-linuxserverio-daapd/?page=4

**Comment by sparklyballs** [comment] 2018-04-10 11:24
pushed another version to linuxserver/daapd:test

this has dbus and avahi started up when you run the image

to use this one first check you have no images or containers of the old version

with `docker ps -a` for containers and `docker images` for images

remove containers with `docker rm -f <CONTAINER ID>`

and images with `docker rmi -f <IMAGE ID>`

run the new container slightly differently with `docker run --rm=true -it --net=host linuxserver/daapd:test bash`


and as before the app is in /app/sbin

**Comment by ejurgensen** [comment] 2018-04-20 22:53
I got the Docker up and running, and I also produced the crash in the debugger, which gave some clues to the problem. It is happening pretty deep inside ffmpeg (something like 9 calls in), and it looks like it could be a threading issue. I have a possible fix for it, which is the above, but I haven't tested it since I didn't get around to setting up a build environment in Docker with all packages needed.

Can you try to build from https://github.com/ejurgensen/forked-daapd/tree/ffmpeg_crash1 and see if it is any improvement?

I also need to learn how to preserve state in Docker, i.e. keep installed stuff when restarting the container. Any pointers on that?

**Comment by ejurgensen** [comment] 2018-04-21 21:29
Got a build in Docker made, and it revealed that my first attempt at a fix (in the now deleted branch ffmpeg_crash1) did not work. After looking into it some more I found what seems to be a working fix, which is in the branch [ffmpeg_crash2](https://github.com/ejurgensen/forked-daapd/tree/ffmpeg_crash1). I hope you can test it soon.

The bug was rather tricky, but I think it is in fact in ffmpeg. There are two jpeg encoding modes, "default" and "optimal", and for some reason in your Docker build the latter is used. However, the optimal mode doesn't seem to work, since it leads straight to a crash. I will experiment a bit more with this and then probably submit it to ffmpeg.

**Comment by ejurgensen** [comment] 2018-04-21 21:42
Seems the bug has already been reported to ffmpeg: https://trac.ffmpeg.org/ticket/6447#no1

Unfortunately they seem to have closed it due to lack of reproducibility, despite a high quality bug report. Sigh.

**Comment by jompjomp** [comment] 2018-04-24 00:28
Thanks for sticking with this, I really appreciate it!

**Comment by ejurgensen** [comment] 2018-05-02 17:59
Closing, no feedback

**Closed by ejurgensen** 2018-05-02 17:59 UTC
