### ISSUE TITLE
can not play flac files in itunes with 27.0

### ISSUE THREAD

**Issue by bendschs** [ejurgensen/forked-daapd#853] opened 2019-12-03 18:28 UTC
Since the newest version i am not able to play flac files with itunes 12.9.5.5 on OSX Mojave.
It's still possible to play the flacs via mpd, but playing them in itunes i get the follwing error message: 

```
[2019-12-03 15:14:48] [DEBUG]     daap: DAAP request handled in 52 milliseconds
[2019-12-03 15:14:48] [DEBUG]    httpd: Read 65536 bytes; streaming file id 6624
[2019-12-03 15:14:48] [DEBUG]    httpd: Read 65536 bytes; streaming file id 6624
[2019-12-03 15:14:48] [DEBUG]    httpd: Read 65536 bytes; streaming file id 6624
[2019-12-03 15:14:48] [DEBUG]    httpd: Read 65536 bytes; streaming file id 6624
[2019-12-03 15:14:48] [DEBUG]    httpd: Read 65536 bytes; streaming file id 6624
[2019-12-03 15:14:48] [ WARN]    httpd: Connection failed; stopping streaming of file ID 6624
```

**Comment by ejurgensen** [comment] 2019-12-03 23:07
I cannot reproduce this with iTunes 12.10.2.3 for Windows, and I don't have OSX. However, your log seems to indicate that forked-daapd is sending the raw flac to iTunes, and I don't think iTunes can handle that. The file should be transcoded by forked-daapd. So the question is why that is not happening.

I don't think it is related to the version of forked-daapd. I think the cause is either iTunes using a different User-Agent, or from iTunes having a different Accept-Codecs header in the request.

If you crank the log level all the way up to spam it should provide some further clues. Could you try that? Also please check what user-agent the log states in this line:
`"[INFO] daap: Client 'iTunes/12.10.2 (...) AppleWebKit/7608.3010.1004.4 (dt:2)' logging in from xxxx"`

**Comment by bendschs** [comment] 2019-12-04 00:38
i can confirm that it works on my other system at the office running 26.5.

**Comment by ejurgensen** [comment] 2019-12-04 10:16
Ok, then I suppose I was wrong. Is it the same flac file? Could you get spam level log from both servers, so I can compare?

**Comment by bendschs** [comment] 2019-12-04 11:12
actually it is fixed now .. i edited the last message after figuring out it was a wron entry in the config file. thank you for your support!

**Comment by ejurgensen** [comment] 2019-12-04 20:00
Glad it wasn't a bug in 27.0, will close the issue then

**Closed by ejurgensen** 2019-12-04 20:00 UTC
