### ISSUE TITLE
OOM error when scanning iTunes library XML

### ISSUE THREAD

**Issue by andersm** [ejurgensen/forked-daapd#191] opened 2015-10-28 21:05 UTC
I'm using the Debian Jessie version on a NAS to serve my iTunes library, and whenever the scanner starts parsing the iTunes Music Library.xml file it starts consuming memory until killed by the OOM killer. The XML file is relatively large at 50MB.

**Comment by ejurgensen** [comment] 2015-10-28 22:04
For other reasons, the iTunes parser has been changed since the version in Jessie, and this may already have fixed the issue. If you are able to try version 23.2 or later it would be great. It not, or if the problem is still there, then I would appreciate if you would share the file (e.g. by emailing me at espenjurgensen@gmail.com).

**Comment by ejurgensen** [comment] 2015-11-10 19:01
Closing, no feedback

**Closed by ejurgensen** 2015-11-10 19:01 UTC
