### ISSUE TITLE
FreeBSD: forked-daapd prone to sporadic segfaults

### ISSUE THREAD

**Issue by floogs** [ejurgensen/forked-daapd#813] opened 2019-09-18 02:51 UTC
The forked-daapd process has been crashing on my FreeBSD machine fairly frequently, but not in a pattern or due to a cause I've been able to find. Sometimes it runs for a week with no issue; other times it lasts a few hours and then dies (I had it crash twice in the last 24 hours, for example).

I get a kernel message similar to this whenever it crashes, which appears to be a segmentation fault.

```
> pid 87340 (forked-daapd), uid 1001: exited on signal 11
```

What would be the best way to track this down? I've tried to catch a crash while the logging is set to a relatively high level, but since I don't have a good way to reproduce the crash, it's been tough to diagnose. I can definitely say that there's nothing out of the ordinary in a typical log-level log prior to a crash as that's what it was set to during the last two crashes. (I think I had it set to debug at one point and didn't see anything unusual then either, but don't quote me on that.)

**Comment by ejurgensen** [comment] 2019-09-18 09:06
Those rare, sporadic errors can be tough to fix. What are the last lines in the log, when it happens?

If the machine you run forked-daapd has some power, you could try running forked-daapd with Valgrind. It will make forked-daapd run a good bit slower, but when the error happens Valgrind will produce very good details on the issue.

I will also try to fire up my FreeBSD vm and see if I can find anything.

**Comment by ejurgensen** [comment] 2019-09-18 20:13
I think I may have been so lucky as to find the issue and have it fixed with this commit 6836a0f. When I took a test run in FreeBSD I did get a segfault, and the cause was incorrect error checking. This bug would only happen when specific types of mdns announcements occur, so it would be sporadic like you describe.

I hope you will try again with an updated forked-daapd, and I will keep my fingers crossed in the meantime.

BTW I couldn't make Valgrind work in FreeBSD, so I used gdb instead.

**Comment by floogs** [comment] 2019-09-19 18:42
Of course (and wow, easiest testing process ever). Obviously it'll take some time, perhaps a couple of weeks of uninterrupted use, before I can say for sure if the crash has been eliminated, but I've got the latest master compiled and running now, so I'll report back after some time has passed.

**Comment by floogs** [comment] 2019-10-09 16:04
I've been running the same instance of forked-daapd for well over two weeks without any segfaults or other issues, so it's probably safe to say you squashed this bug on the first attempt and this can be closed.

One quirk I wanted to mention that's so minor it isn't really worth opening a separate issue for: when browsing available libraries in the iOS Remote app, the icon for the forked-daapd library will often appear greyed out as if it's offline or not eligible for connection, but then tapping the icon will connect as normal anyway. (Normal behavior is for the icon to appear in color when the library is available for connections.) This can be a little confusing, but isn't exactly a showstopper -- just thought I'd mention it in case it's an easy fix.

**Comment by ejurgensen** [comment] 2019-10-09 18:41
Good news, thanks for the feedback.

I have also encountered the Remote issue you mention, and I'm pretty sure it is a bug with Remote. Forked-daapd just makes an mdns announcement to appear in the list, and I don't think there is much I can change about that.

**Closed by ejurgensen** 2019-10-09 18:41 UTC
