### ISSUE TITLE
MP3 playback in iTunes is truncated

### ISSUE THREAD

**Issue by Australis86** [ejurgensen/forked-daapd#1072] opened 2020-08-06 03:12 UTC
I'm running forked-daapd version 27.2 on a Raspberry Pi 3 (running Raspbian 9 Stretch) and have noticed that some MP3 files do not play right to the end; they get truncated/stop partway through and iTunes moves onto the next track. This behaviour occurs whether I play the affected tracks from a M3U playlist (which includes the track length metadata) or via the artist/album options in iTunes. The behaviour isn't consistent, either - I can play a file through without issues one day, then it truncates the next or vice-versa. There also doesn't seem to be a particular point where it cuts out (either as a time or a percentage of the duration).

Each of the sections in the attached log file shows the behaviour when it plays an MP3 and then truncates playback, automatically moving onto the next track. It looks like it thinks the song has finished when it hasn't.
[forked-daapd-log-samples.log](https://github.com/ejurgensen/forked-daapd/files/5032335/forked-daapd-log-samples.log)

I am running iTunes 12.10.8.5 on Windows 10.

**Comment by ejurgensen** [comment] 2020-08-11 09:20
I will see if I can reproduce this, but it sounds like it may be a difficult issue to fix. There is no indication of any problem in the log files, and if the error is very sporadic then it also makes it difficult.

**Comment by Australis86** [comment] 2020-08-11 09:29
Thanks. If there is any further debugging or testing I can do to assist, please let me know. At this stage I'm just not sure what else to try.

**Comment by ejurgensen** [comment] 2020-08-12 08:30
I've tried reproducing, but it has played fine now for a bit more than an hour. I also can't think of any other way to narrow down the cause, unfortunately. Well except if you can find a way of reproducing, or maybe some pattern in when it occurs. Otherwise if there is some way to get logging from your iTunes, but maybe that is unlikely.

Btw how much truncation is that you observe? Like how much is skipped?

**Comment by Australis86** [comment] 2020-08-12 08:34
I'll see what I can to find a way to reliably reproduce it or see if there's any pattern in the behaviour.

Typically it seems to cut off at least a minute of playback. It's always in the last third of the song somewhere, although I haven't found a pattern in where it cuts out yet.

**Comment by Australis86** [comment] 2020-08-14 12:57
I've done some more testing and have a few more comments to add (just in case any of these prompt any ideas).

It seems that only MP3 files with a constant bitrate are truncated, whereas MP3s with a variable bit rate don't. This seems to be irrespective of the source (purchased or ripped from one of my CDs).

I've also been able to identify that roughly half the tracks get truncated (regardless of playback from a custom M3U playlist or automatic album playlist). Still haven't found a pattern in how much gets truncated, though, apart from noting that it's always in the latter half of the track.

Track length also seems to be a factor. The shortest tracks I've seen truncated were around 2:20-2:30 in length (shorter ones from a soundtrack, around 90-100 seconds, do not get truncated).

I will continue to do further testing over the next week and update this issue if I find anything else. So far all playback has been from my desktop PC; I should test from another device and see if that makes any difference.

**Comment by ejurgensen** [comment] 2020-08-14 13:20
Good to know, I will try with some long, constant bitrate tracks. When it comes to mp3's and iTunes, forked-daapd doesn't do much, it just serves the raw file.

Perhaps if you watch the traffic with Wireshark you can find more clues?

**Comment by ejurgensen** [comment] 2020-08-14 22:15
The issue still doesn't reproduce for me. If I compare my log files with yours I notice that mine show a regular pattern of how iTunes reads and buffers. iTunes seems to read ahead with about 30 sec, meaning that the log shows "Done streaming" about 30 sec before playback switches to the next track. The next track is requested by iTunes ("Kicking off streaming...") about 10 sec before playback starts.

Your logs don't show such a pattern. For instance you have "Done streaming file id 227" at 13:08:45 (same time the streaming started!), which is well before the next "Kicking off" at 13:10:04. It is the same with 233 and 234, except 233 is read for a bit longer (21 seconds). So it looks odd, but I don't know what could be causing this.

**Comment by Australis86** [comment] 2020-08-15 01:45
Thanks - that's a good idea to try Wireshark (haven't used it in a few years, so will have to refresh my memory) to see if there's any info there.

What is even more puzzling is that I have been running iTunes (same version) on my MS Surface Pro 3 (also running Windows 10) and it hasn't truncated any files. This suggests it has to do with my desktop or how the desktop is interacting with forked-daapd, so it's possible that this isn't an issue with forked-daapd at all (which may be why you can't reproduce it).

I've attached the latest log file which includes all the playback from yesterday (when it was truncating CBR files on my desktop) and today's playback (no truncation on my Surface).

Entries up to [2020-08-14 21:20:29] are VBR files that didn't truncate.
Entries from [2020-08-14 21:48:32] to [2020-08-14 23:08:02] are CBR files (about half of which were truncated during playback)
All the entries dated today (2020-08-15) are from my Surface and didn't exhibit any truncation.

[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/5077985/forked-daapd.log)

**Comment by Australis86** [comment] 2020-08-17 11:18
I can confirm it's specific to iTunes on my desktop now. The DAAP Player from the Windows store doesn't suffer the truncation issue, so that would suggest it is either iTunes entirely or the way iTunes is interacting with forked-daapd.

I'll do some more debugging during the week, but my guess is that this is going to turn out to be an issue solely with my particular iTunes installation.

**Comment by LordMyschkin** [comment] 2020-08-17 12:23
May I just throw in that I too noticed sometimes truncated playback - may
well be that it is just from truncated songs (as I assumed, why i never
went after), but it was a few times too often to rely on that.
I will watch that issue closely - I do not use iTues, just play the tracks
from my SSD.



Am Mo., 17. Aug. 2020 um 13:18 Uhr schrieb Joshua <notifications@github.com

**Comment by ejurgensen** [comment] 2020-08-18 14:12
I just noticed that Stretch has libevent 2.0 (pretty old...). I can see that forked-daapd [has a limitation with that version](https://github.com/ejurgensen/forked-daapd/blob/master/src/httpd.c#L654), which means that it can only stream to one client at a time. So I am wondering if the issue here comes from you having multiple clients?

Buster has 2.1 where this issue should not exist.

**Comment by Australis86** [comment] 2020-08-19 10:17
> > I just noticed that Stretch has libevent 2.0 (pretty old...). I can see that forked-daapd [has a limitation with that version](https://github.com/ejurgensen/forked-daapd/blob/master/src/httpd.c#L654), which means that it can only stream to one client at a time.

I think you've cracked it! After looking at this, I did an in-place upgrade of my Pi from Raspbian 'Stretch' to 'Buster' and retested today. So far, I don't think any files have been truncated (one I'm not sure about... not sure if I accidentally skipped it - but even if it was truncated, it's a vast improvement from roughly every second track down to about 1 in 30). I'll keep testing and report back later this week if I note any other truncated files.

Makes me wonder what iTunes on my desktop was trying to do with CBR MP3s - was it sometimes trying to stream the start of the next file before the previous one finished? And if so, why only on some files and not others and why only CBR MP3s? Weird. Hopefully this is the end of the problem on my setup.

@LordMyschkin, I have to wonder if it's a distinct problem to the one I have been experiencing. Is your setup similar to what mine was (Raspbian 'Stretch' as the forked-daapd host)?

**Comment by ejurgensen** [comment] 2020-08-19 14:42
That's good to hear. I'll close the issue, we can reopen if it turns out that the issue isn't fixed.

**Closed by ejurgensen** 2020-08-19 14:42 UTC

**Comment by Australis86** [comment] 2020-08-20 08:56
Thanks for all the help and support so far. Unfortunately it's still truncating tracks, although far less frequently than it was (only had 2 truncated in the last hour).

**Comment by Australis86** [comment] 2020-08-25 07:50
Further testing today only produced one truncated track (which, intriguingly, was a VBR MP3 file this time - the first time that's happened). I haven't had a chance to look at the wireshark traffic, though, nor try removing and reinstalling iTunes to see if that fixes the problem (that's next on my list).

**Comment by dingho** [comment] 2021-02-16 07:46
I'm getting this same issue.  daapd server running on an unRAID docker (https://hub.docker.com/r/linuxserver/daapd/).  This is on a fresh install of Win10 and iTunes.  The mp3 itself doesn't seem to be the issue, as the same file will be truncated of the last few seconds, but then play completely the next time it plays.
I tried to look at some Wireshark captures, but I don't think I'm smart enough to figure out what's going on there.
Watching the log shows nothing unusual.  Anything else I can supply to help?

**Comment by Australis86** [comment] 2021-03-10 11:07
Apologies for the delay in responding to your comment, @dingho. I have still occasionally had tracks get truncated (usually only one or two an hour), but it looks like there has just been a new release. I'll have to test again (just updated to forked-daapd 27.2) and see what the results are.

I never found anything in the log and never got around to looking at Wireshark captures closely once it became less frequent.

**Comment by Australis86** [comment] 2021-03-12 05:15
I've done further testing today with 27.2 and unfortunately the problem still occasionally occurs. If I ever have time I'll try looking at Wireshark.

**Comment by dingho** [comment] 2021-03-12 08:33
The docker image got updated as well.  I'm still getting the same problem.
