### ISSUE TITLE
Output delay, reset causes web interface to show next track info instead of reset track

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#781] opened 2019-07-27 21:47 UTC
I have noticed that sometimes when a track is ending and the next track starts there is some sort of very short ‘blip’ and the next track starts to play

Looking in the log I can see this which happens at the end of the track.
```
07-27 21:50:19] [  LOG]    cache: Beginning DAAP cache update
[2019-07-27 21:50:19] [  LOG]    cache: DAAP cache updated
[2019-07-27 21:54:22] [  LOG]    cache: Beginning DAAP cache update
[2019-07-27 21:54:22] [  LOG]    cache: DAAP cache updated
[2019-07-27 22:33:26] [  LOG]   player: Output delay detected (behind=193, max=150), resetting all outputs
[2019-07-27 22:33:31] [  LOG]   player: Output delay detected (behind=193, max=150), resetting all outputs
```
The tracks that were being played were all 44.1/stereo but varying bitrate (128 m4a going into 320 mp3) and this is reproducible with those 2 tracks on my rpi3; unfortunately copying the same files to another machine does NOT generate the error.

The player does the reset on the next track (320mp3) and it plays the track in the correct order.

What is confusing is on the web interface it shows an apparent skip to the subsequent track: track 2 (the 320 mp3) is playing but web interface shows track 3 info on now playing page

I’ll take a quick walk of the code to see if there’s a spurious notif

**Comment by whatdoineed2do** [comment] 2019-07-28 10:10
This is the log file of this happening - I start the server, navigate to the web i/f Q page, select track#1 (129kbps m4a) and then skip to about 10secs before end of track.

[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/3439033/forked-daapd.log)

The sequence:
* playing track#1 (item-id=250) and it comes to an end
* track#2 (item-id=241) is being prep'd via `event_read_start_next()`
* reports of `Output delay...`
* resume of playback of track#1 (item-id=250)
* `event_read_start_next()` is called BUT it finds track#3 (item-id=242) -- **the bug**
* resume of playback of track#2 (item-id=241)

However the player status believes we are on track#3 (item-id=242) as seen in the REST call even though its correctly playing track#2 (item-id=241)
```
{
  "state": "play",
  "repeat": "off",
  "consume": false,
  "shuffle": false,
  "volume": 100,
  "item_id": 242,
  "item_rating": 40,
  "item_length_ms": 352888,
  "item_progress_ms": 107033,
  "artwork_url": "/artwork/nowplaying"
}
```

**Comment by ejurgensen** [comment] 2019-07-28 19:00
Very good investigation, I think that should provide a good base for fixing the bug. I’m away for a few weeks so I can’t do it right now. 

It would be interesting if you could also identify the cause of the output delay. It isn’t really supposed to happen. You could maybe add some timing around output_write() in player.c to check if it is sometimes slow. It should never use more than 1/100th of a second.

**Comment by whatdoineed2do** [comment] 2019-07-28 19:12
Sure thing, thanks.  I was walking through the code this evening and I can't really see where the delay is coming from but will give it another look on the daily commute next week but the pain is that only happens on my rpi3: same tracks, same order doesn't result n the same problem on any other machine.

One thing to add is that when the server is playing track#2 (but displaying track#3 on the web browser) when we skip forward on that, the server does open track#3 so the server's internal state (item_id) referring to track#3 is kinda correct.  The transition out of track#1 on web i/f's "now playing" page does very briefly flash up track#2's details before then displaying track#3's details whilst continuing to play track#2

**Comment by whatdoineed2do** [comment] 2019-07-28 21:25
I add some very simple `gettimeofday` around the `outputs_write` and I do get a few occurances  where it takes more than 1/100th
```
[2019-07-28 22:22:28] [  LOG]   player: outputs_write() late: 0.019441
[2019-07-28 22:22:30] [  LOG]   player: outputs_write() late: 0.032967
[2019-07-28 22:22:31] [  LOG]   player: outputs_write() late: 0.015146
[2019-07-28 22:22:33] [  LOG]   player: outputs_write() late: 0.053655
[2019-07-28 22:22:45] [  LOG]   player: outputs_write() late: 0.033884
[2019-07-28 22:22:47] [  LOG]   player: outputs_write() late: 0.048294
[2019-07-28 22:22:50] [  LOG]   player: outputs_write() late: 0.025343
[2019-07-28 22:22:52] [  LOG]   player: outputs_write() late: 0.040124
```
[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/3439583/forked-daapd.log)

**Comment by ejurgensen** [comment] 2019-08-01 15:54
To proceed with this you could also have the timing measurement in alsa.c, around snd_pcm_write(). Check if it is blocking. Also log the avail variable to see if it is particularly low when and if it blocks.

**Comment by whatdoineed2do** [comment] 2019-08-01 16:40
will do, thanks.

I think there are 2 issues here though:
* why this setup blocks / delayed performing writes
* handling around _output resets_ that seems to lead to premature eof (on reading item 241) and then the internal state (jumping to the next track in queue, 242)

Will dig through and see what I can find - was trying to get my head around the various threads in player.c to figure out what happens after the reset.

**Comment by whatdoineed2do** [comment] 2019-08-01 20:40
I put a 1 ms limit around the `snd_pcm_write()` calls and 100ms around `outputs_write() and they (mostly?) line up:
```
[2019-08-01 21:24:17] [  LOG]   player: outputs_write() late: 0.032024  item-id=250 sec=10465373
[2019-08-01 21:24:19] [  LOG]   player: alsa buffer_write() late: 0.046435  X  avail=131072 ret=85113
[2019-08-01 21:24:19] [  LOG]   player: outputs_write() late: 0.047695  item-id=250 sec=10465375
[2019-08-01 21:24:21] [  LOG]   player: outputs_write() late: 0.026460  item-id=250 sec=10465377
[2019-08-01 21:24:23] [  LOG]   player: alsa buffer_write() late: 0.046156  X  avail=131072 ret=85113
[2019-08-01 21:24:23] [  LOG]   player: outputs_write() late: 0.048838  item-id=250 sec=10465378
[2019-08-01 21:24:34] [  LOG]   player: outputs_write() late: 0.033789  item-id=250 sec=10465390
[2019-08-01 21:24:35] [  LOG]   player: outputs_write() late: 0.020658  item-id=250 sec=10465390
[2019-08-01 21:24:36] [  LOG]   player: alsa buffer_write() late: 0.044321  X  avail=131072 ret=85113
[2019-08-01 21:24:36] [  LOG]   player: outputs_write() late: 0.045501  item-id=241 sec=10465392
[2019-08-01 21:24:39] [  LOG]   player: outputs_write() late: 0.030580  item-id=241 sec=10465395
[2019-08-01 21:24:41] [  LOG]   player: alsa buffer_write() late: 0.042540  X  avail=131072 ret=86877
[2019-08-01 21:24:41] [  LOG]   player: outputs_write() late: 0.044414  item-id=242 sec=10465397
```
As for the `avail` value, its the same size ( 131072) of of the alsa buffer in the dump'd config.

Will keep digging, but FWIW heres the log:
[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/3458556/forked-daapd.log)

But looking at the logs earlier today, I think the sequence is this:
* play (250)
* eof
* new track q (241)
* output delay, restting ...
* resume of playback (250)
* eof
* play (241)
* get next track (using 241) !!!! == 242
* play (242)

**Comment by whatdoineed2do** [comment] 2019-08-03 15:02
I think I understand the problem now.  Attached is the log file for the investigation which should play `item_id` 250, 241 and then 242 in that order.

[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/3463945/forked-daapd.log)

What is important is the call stack from `event_read_start_next()`:
```
event_read_start_next()
    player_source* ps = source_next_create(pb_session.source_list)
        -- get from db based on current->item_id
        queue_item = queue_item_next(current->item_id)
        ps = source_creat(queue_item)
    session_update_read_next(ps)         -- pb_session.source_list = ps
    source_next(pb_session.source_list)  -- points at newly created ps->item_id
        input_start()
```

The following is what happens (first column/far left is the line number to the log)
```
 58  event_play_start(250)
       playing ... 
116  event_read_start_next()
       db fetch based on item-id=250, returns 241
123    db fetch by pos 241
126    "Opening next track" 241
130    "Setting up input" 241
132  event_eof (250)
133  "Incomplete read" (250)

161  "resetting all outputs" 
171  "Resuming playback" 250
172  "Restarting track" 250
182  "Setting up input item" 250
206  "Starting input read loop" 250

237  event_read_start_next()
246  db fetch based on item-id=241, returns 242 ----- why its using 241 ????
     db fetch by pos 242
247  "Opening next track" 242
251  "Setting up input" 242
253  event_play_eof(250)
256  new item id = 241
265  "Incomplete read" (241)
 
293  resetting all outputs
303  Resuming playback 241
304  Restarting track 241
314  Setting up input 241
342  event_play_eof() 241
345  new item_id = 242 (pb_session.playing_now->item_id)
346  event_play_start(242)
```
The problem appears to be that when `item_id=250` is nearing the end, we get ready with the next track (log #116) and thus the `pb_session.source_list` is updated with `item_id=241` which is normal.  track `item_id=250` at this point is still _playing_

However at log#161, we get a forced output resets whilst still playing`item_id=250`.  We clear a few things down, and restart (log#172..206).  Now the end of the track is observed again but at log#237 we want to add the new track to `pb_session.source_list` but this list has `item_id=241` already at the head so  getting the dteails of the 3rd track (`item_id=242`) prematurely.

Then in a different (thread) we start to play `item_id=241`) but the player believes we're actually with `item_id=242` (as seen by the `get_status()` via the REST i/f)

Essentially, the reset near the end of track `item_id=251` results in the `event_read_start_next()` being called twice leading to the player state _skipping_ the 2nd track.

I'll see if I can dig around for a fix to validate queue positions in `event_read_start_next` but @ejurgensen suggestions for a fix to this scenario are very welcome!

**Comment by ejurgensen** [comment] 2019-08-03 15:48
Thanks for the investigation, but I prefer to make the fix for that part of the issue myself. 

It would be good if you could dig more into the delay issue. It is for instance odd that avail has the size of the entire buffer (?). So maybe check if the device is just always giving that value?

**Comment by whatdoineed2do** [comment] 2019-08-03 19:46
For buffer size, I enabled the prebuffer writing/drain debug lines in `alsa.c` and this is what we see.

```
[2019-08-03 20:36:44] [DEBUG]   laudio: Dump of sound device config:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S32_LE
  subformat    : STD
  channels     : 2
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 32
  buffer_size  : 131072
  period_size  : 1024
  period_time  : 23219
  tstamp_mode  : ENABLE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 1024
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 131072
  silence_threshold: 0
  silence_size : 0
  boundary     : 1073741824


[2019-08-03 20:36:44] [  LOG]   player: outputs_write() late: 0.022701  item-id=250 sec=10635320
[2019-08-03 20:36:46] [DEBUG]   laudio: Writing prebuffer (read_avail=0, bufsize=680904, avail=131072)
[2019-08-03 20:36:46] [  LOG]   player: alsa buffer_write() late: 0.044207  X  avail=131072 ret=85113
[2019-08-03 20:36:46] [  LOG]   player: outputs_write() late: 0.045627  item-id=250 sec=10635322
2019-08-03 20:36:47] [  LOG]   player: outputs_write() late: 0.025354  item-id=250 sec=10635323
[2019-08-03 20:36:49] [DEBUG]   laudio: Writing prebuffer (read_avail=0, bufsize=680904, avail=131072)
[2019-08-03 20:36:49] [  LOG]   player: alsa buffer_write() late: 0.044132  X  avail=131072 ret=85113
[2019-08-03 20:36:49] [  LOG]   player: outputs_write() late: 0.045459  item-id=250 sec=10635325
2019-08-03 20:37:01] [  LOG]   player: outputs_write() late: 0.028324  item-id=250 sec=10635337
[2019-08-03 20:37:01] [  LOG]   player: outputs_write() late: 0.014508  item-id=250 sec=10635337
[2019-08-03 20:37:03] [DEBUG]   laudio: Writing prebuffer (read_avail=0, bufsize=680904, avail=131072)
[2019-08-03 20:37:03] [  LOG]   player: alsa buffer_write() late: 0.046314  X  avail=131072 ret=85113
[2019-08-03 20:37:03] [  LOG]   player: outputs_write() late: 0.047864  item-id=241 sec=10635339
[2019-08-03 20:37:03] [DEBUG]   laudio: Draining prebuffer (read_avail=0, bufsize=1304, avail=46887)
[2019-08-03 20:37:03] [  LOG]   player: outputs_write() late: 0.010772  item-id=241 sec=10635339
2019-08-03 20:37:06] [  LOG]   player: outputs_write() late: 0.027328  item-id=241 sec=10635342
[2019-08-03 20:37:08] [DEBUG]   laudio: Writing prebuffer (read_avail=0, bufsize=347508, avail=131072)
[2019-08-03 20:37:08] [  LOG]   player: alsa buffer_write() late: 0.042552  X  avail=131072 ret=86877
[2019-08-03 20:37:08] [  LOG]   player: outputs_write() late: 0.043872  item-id=242 sec=10635344
```

**Comment by whatdoineed2do** [comment] 2019-08-09 14:14
I took the sample tracks onto my desktop which does not suffer the `Output delay... resetting all outputs` and played them through - the query you raised about `avail` "avail has the size of the entire buffer"

It appears that this is the same the desktop (below) and the RPi3:

* desktop log playing track1
```
[DEBUG]   player: New session values (q=44100/32/2, spr=441, bufsize=3528)
[DEBUG]   laudio: Adding playback session (quality 44100/32/2) to ALSA device 'default'
[DEBUG]   laudio: Dump of sound device config:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S32_LE
  subformat    : STD
  channels     : 2
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 32
  buffer_size  : 524288
  period_size  : 512
  period_time  : 11609
  tstamp_mode  : ENABLE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 512
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 524288
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904

[DEBUG]   player: Player status: playing (buffering)
[DEBUG]   laudio: Writing prebuffer (read_avail=0, bufsize=680904, avail=524288)
[  LOG]   player: alsa buffer_write() late: 0.002261  X  avail=524288 ret=85113
```

* rpi3 log playing track1
```
[DEBUG]   player: New session values (q=44100/16/2, spr=441, bufsize=1764)
[DEBUG]   laudio: Adding playback session (quality 44100/16/2) to ALSA device 'dac'
[DEBUG]   laudio: Dump of sound device config:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 16
  buffer_size  : 131072
  period_size  : 1024
  period_time  : 23219
  tstamp_mode  : ENABLE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 1024
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 131072
  silence_threshold: 0
  silence_size : 0
  boundary     : 1073741824

[  LOG]   player: outputs_write() late: 0.028219  item-id=255 sec=11132356
[DEBUG]   player: Player status: playing (buffering)
[DEBUG]   laudio: Writing prebuffer (read_avail=0, bufsize=347508, avail=131072)
[  LOG]   player: alsa buffer_write() late: 0.039622  X  avail=131072 ret=86877
[  LOG]   player: outputs_write() late: 0.040863  item-id=255 sec=11132358
[ WARN]   player: Output delay detected: player is 3 ticks behind, catching up
```

**Comment by ejurgensen** [comment] 2019-08-09 14:49
avail will always equal buffer size before writing (which the above is from). During playback it should not be equal, because that would be an underrun. I think your previous log was from during playback, but there was no underrun.

**Comment by whatdoineed2do** [comment] 2019-08-09 17:18
excuse that brain failure there.. the following is the extra log above the other `snd_pcm_writei()` in `buffer_write`.
```
DPRINTF(E_DBG, L_LAUDIO, "Writing to device (bufsize=%zu, avail=%li, samples=%d)\n", odata->bufsize, avail, odata->samples);
```
Playing a 5 sec sine sweep for some reference.

* desktop, 324 different values for avail=438619..439650
```
DEBUG]   laudio: Dump of sound device config:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S32_LE
  subformat    : STD
  channels     : 2
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 32
  buffer_size  : 524288
  period_size  : 512
  period_time  : 11609
  tstamp_mode  : ENABLE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 512
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 524288
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904

[DEBUG]   player: Player status: playing (buffering)
[DEBUG]   laudio: Writing prebuffer (read_avail=0, bufsize=680904, avail=524288, samples=85113)
[  LOG]   player: alsa buffer_write() late: 0.002008  X  avail=524288 ret=85113
[DEBUG]   laudio: Writing to device (bufsize=3528, avail=439175, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=3528, avail=438734, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=3528, avail=438845, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=3528, avail=438924, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=3528, avail=439019, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=3528, avail=439146, samples=441)
```
* RPI3 - 35 different values for avail=44131..45514
```
[DEBUG]   laudio: Dump of sound device config:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 16
  buffer_size  : 131072
  period_size  : 1024
  period_time  : 23219
  tstamp_mode  : ENABLE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 1024
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 131072
  silence_threshold: 0
  silence_size : 0
  boundary     : 1073741824

[  LOG]   player: outputs_write() late: 0.032263  item-id=255 sec=11142906
[ WARN]   player: Output delay detected: player is 2 ticks behind, catching up
[DEBUG]   player: Player status: playing (buffering)
[DEBUG]   laudio: Writing prebuffer (read_avail=0, bufsize=347508, avail=131072, samples=86877)
[  LOG]   player: alsa buffer_write() late: 0.039688  X  avail=131072 ret=86877
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44195, samples=441)
[  LOG]   player: outputs_write() late: 0.041008  item-id=255 sec=11142908
[ WARN]   player: Output delay detected: player is 3 ticks behind, catching up
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=45514, samples=441)
[DEBUG]   player: event_play_start() item_id=255
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=45117, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44712, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44311, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44134, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44133, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44136, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44135, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44134, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44133, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44132, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44135, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44134, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44133, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44132, samples=441)
[DEBUG]   laudio: Writing to device (bufsize=1764, avail=44135, samples=441)
```

And below is the log for the same test cases as the original problem with these log lines, where the avail size ranges from 44130..58734, although the higher values all appear at the start of the playback
[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/3487324/forked-daapd.log)

**Comment by ejurgensen** [comment] 2019-08-16 23:58
I've made an attempt at fixing the part of the issue with wrong playback status in the playersuspend1 branch. It wasn't a very easy issue to solve, since that part of playback control is complicated. It is possible there is something I have overlooked, and more work is required.

I hope you will test it. I will also do some more testing.

**Comment by whatdoineed2do** [comment] 2019-08-17 08:38
Many thanks.  I cherry pciked those commits into my branch with the extra logging and everything seems good with the exact same scenario no longer failing (ie not skipping to 3rd track).

Regarding the delay to the alsa `snd_pcm_writei` I was not able to see any errors that caused the slow write - in most cases the write would be below 0.0004 but there were a few that crept past .0007 and one that hit 0.004 so don't know if this is just something related to the DAC card on this RPI.
```
$ grep -v "duration=0.000[1-6]" forked-daapd.log | grep "Writing to devi"
[2019-08-17 09:17:52] [DEBUG]   laudio: Writing to device (bufsize=3528, avail=45633, duration=0.000731)
[2019-08-17 09:17:53] [DEBUG]   laudio: Writing to device (bufsize=3528, avail=45638, duration=0.000751)
[2019-08-17 09:18:14] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44131, duration=0.002020)
[2019-08-17 09:18:15] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44135, duration=0.001705)
[2019-08-17 09:19:16] [DEBUG]   laudio: Writing to device (bufsize=3528, avail=45688, duration=0.000768)
[2019-08-17 09:19:43] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44135, duration=0.000909)
[2019-08-17 09:19:45] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44134, duration=0.000968)
[2019-08-17 09:19:52] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44135, duration=0.000774)
[2019-08-17 09:19:53] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44131, duration=0.000719)
[2019-08-17 09:21:12] [DEBUG]   laudio: Writing to device (bufsize=3528, avail=32519, duration=0.001776)
[2019-08-17 09:21:16] [DEBUG]   laudio: Writing to device (bufsize=3528, avail=32524, duration=0.000917)
[2019-08-17 09:21:40] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44125, duration=0.002936)
[2019-08-17 09:21:42] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44138, duration=0.002579)
[2019-08-17 09:21:44] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44128, duration=0.001003)
[2019-08-17 09:21:44] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44128, duration=0.002798)
[2019-08-17 09:21:50] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44123, duration=0.004182)
[2019-08-17 09:21:52] [DEBUG]   laudio: Writing to device (bufsize=1764, avail=44122, duration=0.001195)
```
Whilst experimenting/trying to avoid this issue I did set `PLAYER_WRITE_BEHIND_MAX 2000` and that seemed to be enough to suppress the delays on this DAC and not lead to  the original problem  but dont know if this would be a problem if included in the the main trunk - even with the fix, when the reset happens, it takes 2-3 sec to start playing the new track.

I will integrate the fixes for my main server instance and send music through it over the next few days and report any other issues but right now it looks good.

**Comment by whatdoineed2do** [comment] 2019-08-17 09:42
Actually hold that thought - just had the server lock up after it reported an delay/reset outputs

Will dig and report back

**Comment by whatdoineed2do** [comment] 2019-08-17 12:12
In the play Q i have 2 tracks: mp3/48k/320kbps file followed by a mp3/44.1k/320kbp file.

As the track gets to the end of the first track, I see a `resetting all outputs` and the player does not progress to the next track.  Querying the server, it thinks it is paused

The log shows me starting the play and skipping to near the end where issue appears
[reset-fix-pauseissue.log](https://github.com/ejurgensen/forked-daapd/files/3511976/reset-fix-pauseissue.log)
Switching the 2 tracks above around also exhibits this problem, but typically going from 44.1k to 44.1k files is fine.

Will keep digging...

**Comment by ejurgensen** [comment] 2019-08-18 19:47
Good job testing. I am able to reproduce this issue. The quality change is indeed the cause. Looking into a fix...

**Comment by ejurgensen** [comment] 2019-08-18 21:21
I've added some commits to hopefully fix the issue you observed when testing the branch. I think two things were happening, one was that changing the quality of the device during track change caused it to block -> output delay. That caused forked-daapd to reset, but then the restart trigger wasn't firing because it is based on the input reading data across a threshold. However, since the track was just about finished that threshold was never crossed, and the player stayed paused.

So output delay during quality change will still be there, but now forked-daapd should do the reset better (and also quicker).

**Comment by whatdoineed2do** [comment] 2019-08-18 22:26
Nice thanks - the latest commits are good for all the troublesome scenarios I've seen so far

I'll play a large chunk of my library through the new code over next few days and review the logs/report any new issues

**Comment by whatdoineed2do** [comment] 2019-08-18 22:26
Nice thanks - the latest commits are good for all the troublesome scenarios I've seen so far

I'll play a large chunk of my library through the new code over next few days and review the logs/report any new issues

**Comment by whatdoineed2do** [comment] 2019-08-19 17:28
I've sent about 98 tracks /7 hrs of music through the server today and the logs look clean except for the `output delay ... resetting all outputs` msgs (which coincidentally have delays from 191..197ms and are always for the same tracks and the same of delay).

The tracks were mostly mp3/flacs at 44.1k with a few (about 10) 48k files interleaved in the queue.  The delays reported are not always on a transition between sample rates (I added the `item_id` to the `resetting all outputs` log line).

So I think the fixes are good now.  Very much appreciate the fixes for this.

**Comment by ejurgensen** [comment] 2019-08-19 19:35
That's good to hear. I have merged the changes now.

With regard to the delay, the value logged is actually clock ticks. A clock tick is normally 10 ms, so the delay is just about 2 seconds. This value coincides with the buffer length, so I'm thinking what is happening is:

1) Open new track with new quality
2) Open a new ALSA session with the new quality (old one is still active and will remain active for 2 seconds, i.e. until the buffer is empty and closed the session)
3) Writes to the new session are blocked by ALSA until the old one is closed, causing the output delay

Alternatively, it might be step number 2 that blocks until the old session is closed. I don't have much evidence that this is what happening, but if I am right it would mean that this issue is related to issue #742.

In any case I will close this issue, since the current way of dealing with this blocking should offer a reasonable playback experience. The alternative would be to refactor alsa.c to make it non-blocking, and I'm not up to that right now.

**Closed by ejurgensen** 2019-08-19 19:35 UTC
Labels: bug
