### ISSUE TITLE
Spotify Login failed

### ISSUE THREAD

**Issue by kimme1024** [ejurgensen/forked-daapd#1151] opened 2020-12-24 12:11 UTC
Please try to provide the following:

- steps to reproduce and/or logging of the error
Go to webinterface, fill in username&password, click Login
--> takes a bit of time after which a red text "login failed" appears

- version of forked-daapd
latest
- platform
raspbian

I'm already using forked-daapd successfully on another RPi(3) which I configured yesterday the exact same way. As I need another instance running to have access to my wife's Spotify account I decided to run it on another RPi(2). As I have the login screen in the webinterface I assume that Spotify is running. I also installed libspotify-dev without any issues.

**Comment by ejurgensen** [comment] 2020-12-24 12:18
What does the log say?

**Comment by kimme1024** [comment] 2020-12-24 12:29
[2020-12-24 11:59:28] [  LOG]  spotify: Spotify credentials, logging in with username '******e--v' (libspotify)
[2020-12-24 11:59:58] [  LOG]  spotify: Login failed: Cannot connect to Spotify
[2020-12-24 11:59:59] [  LOG]  spotify: No spotify refresh token found

Could it be that the "--" gives an error?
I also tried to use the emailaddress but same error

**Comment by kimme1024** [comment] 2020-12-24 12:39
Also, when I try to connect to Spotify via PI2 (which fails), it changes the Spotify Web API login on my other PI to my wife's login which makes it to display her playlist instead of mine. This also happens when trying to login via another browser, with incognito mode on. Doesn't make sense at all...

**Comment by ejurgensen** [comment] 2020-12-24 13:51
That sounds very weird indeed. I have no clue what might be going on with regard to the latter.

As I recall the errors in the log are precise, so when it says no connection, then that's indeed the issue. You can also see that it has tried for 30 seconds, which I think wouldn't be the case if the credentials were incorrect.

**Comment by ejurgensen** [comment] 2020-12-24 14:16
Come to think of it, I know what happened between the two RPis. When you log in via the web API, the Spotify redirects the browser to forked-daapd.local with the authorization token (OAuth login). So if you have two instances of forked-daapd on the same network there is a risk that the redirect is to the wrong instance. The short story is that you need to only have one instance running when you do the login. It will only be an issue at that exact time.

**Comment by kimme1024** [comment] 2020-12-24 15:53
> Come to think of it, I know what happened between the two RPis. When you log in via the web API, the Spotify redirects the browser to forked-daapd.local with the authorization token (OAuth login). So if you have two instances of forked-daapd on the same network there is a risk that the redirect is to the wrong instance. The short story is that you need to only have one instance running when you do the login. It will only be an issue at that exact time.

Hi thanks for the reply!

Sadly this isn't the case I guess... First of all, the Spotify Web API Auth failed for me on my account as well. It's only now that somehow it succeeded. But even if I click on it I immediately get a "Forbidden"-page.

I tried stopping the service on the first pi, restarting it on the second and logging in but it still fails and the logs are exactly the same...

**Comment by ejurgensen** [comment] 2020-12-25 23:32
I'm not sure I understand your last reply. Be aware that you are dealing with two separate issues, one is that you can't login with your wife's account via libspotify, the other is that your wife's playlist showed up on your RPi2. So for the latter issue I'm confident that the reason is the one I gave, i.e. the redirect from spotify.com's login page with the token went to your RPi2, not the RPi3 as you intended. This is because both instances will announce the dns name forked-daapd.local, so you can't be sure where the redirect goes.

For the issue where you can't login via libspotify (which is the issue where you see the error in the logs), I have just tested to see if I could login, and it worked fine. So I still think it is a connection problem. If there was an issue with the credentials you would see a message about Bad username/password.

**Comment by kimme1024** [comment] 2020-12-26 11:03
@ejurgensen first of all Merry Christmas! :)

I'll try to explain the situation a bit better:

I'm having 2 RPi's:

RPi3, my home automation device.
A couple of days ago I've installed forked-daapd on this device, configured it and it works fine. The only thing I couldn't do was to the web API auth, but as it worked fine I didn't bother that much.

RPi2, a device that intercepts my pelletstove's signals and converts them to MQTT.
As I want to use 2 accounts to be able to use different playlists I installed forked-daapd on this device as well and installed libspotify-dev. On this device I'm getting the login error.

Your explanation about the redirect makes sense as when I tried to do the web API auth on RPi2, suddenly it did the auth on RPi3, which made that suddenly my wife's playlists were visible on RPi3. In the settings I was then logged in with my account, but the web API auth was done on my wife's username. When I clicked on web API auth on RPi3 and tried do to it with my login details, I've got the message "Forbidden" again but after that I suddenly had the authorization on my account. Very weird!

As you advised, I stopped the service on RPi3, restarted (just to be sure) on RPi2 and tried to login on my wife's account on RPi2. Sadly without any success...

I'm a bit hesitant to logout on my RPi3 and try to login with my account on RPi2 and login with my wife's account on RPi3 as I'm a bit worried that I will end up with none of them working.

I hope this makes a bit more sense. Thanks for the great support!

**Comment by ejurgensen** [comment] 2020-12-26 12:55
Merry Christmas to you too! It's clearer now, but it would be more clear if you were specific about what kind of login, when you mention a login. As you know, libspotify login is completely different from web API, and you need to complete both.

If you are happy with the state of RPi3 as it is now then you can make a backup of` /var/cache/forked-daapd`, because that is where authorization tokens for libspotify (in the subdir libspotify) and web api (in songs3.db) are kept in a standard installation. Or you can just stop the service on the RPi3 while you work on getting the RPi2 to work.

**Comment by kimme1024** [comment] 2020-12-26 17:51
Ok, I'll try to explain:

I'll try to explain the situation a bit better:

2 users:

K & S

I'm having 2 RPi's:

RPi3, my home automation device.
A couple of days ago I've installed forked-daapd on this device, configured it and it works fine. The only thing I couldn't do was to login into the web API auth with K, but as it worked fine I didn't bother that much.

RPi2, a device that intercepts my pelletstove's signals and converts them to MQTT.
As I want to use 2 accounts to be able to use different playlists I installed forked-daapd on this device as well and installed libspotify-dev. On this device I'm getting the login error with S (and K, doesn't make a difference).

Your explanation about the redirect makes sense as when I tried to do the web API auth on RPi2 with S, suddenly it did the auth on RPi3 with S, which made that suddenly my wife's (S) playlists were visible on RPi3. In the settings I was then logged in with my account (K), but the web API auth was done on my wife's username (S). When I clicked on web API auth on RPi3 and tried do to it with my login details (K), I've got the message "Forbidden" again but after that I suddenly had the authorization on my account (K). Very weird!

As you advised, I stopped the service on RPi3, restarted (just to be sure) on RPi2 and tried to login on my wife's  (S) account on RPi2. Sadly without any success...

I also tried to login on the RPi2 with my account (K) while RPi3 was stopped and it also didn't work.

I hope this makes a bit more sense. Thanks for the great support!

**Comment by kimme1024** [comment] 2020-12-28 17:08
@ejurgensen Just to be sure I did an `apt upgrade` but it didn't solve the issue.

**Comment by ejurgensen** [comment] 2020-12-28 21:52
Sorry to hear the issue is still there. Since I am unable to reproduce, I don't think there is a general issue, and I also can't think of much else to suggest to you. For the RPi2 I understand you get "Login failed: Cannot connect to Spotify" when you try to authorize libspotify, so maybe try putting it on another network? Might also be worth checking permissions, forked-daapd/libspotify needs to be able to write to the locations you can see in the config file (see spotify settings, settings_dir and cache_dir).

I will close the issue since I'm running out of ideas :-(

**Closed by ejurgensen** 2020-12-28 21:52 UTC

**Comment by kimme1024** [comment] 2020-12-29 14:29
Thanks for trying!
I gave permissions to the directories, sadly without success...

I tried installing on macos but some of the steps didn't work so I couldn't finish it...

antlr3, didn't work via commandline, installed it from their website 
but then this got me stuck completely:
```
Warning: autoconf 2.69 is already installed and up-to-date
To reinstall 2.69, run `brew reinstall autoconf`
Warning: automake 1.16.3 is already installed and up-to-date
To reinstall 1.16.3, run `brew reinstall automake`
Warning: libtool 2.4.6_2 is already installed and up-to-date
To reinstall 2.4.6_2, run `brew reinstall libtool`
Mac-mini-van-Kim:~ XBMC$ autoreconf -fi
autoreconf: 'configure.ac' or 'configure.in' is required
```
tried reinstalling autoconf, automake and libtool but they were installed in previous steps.
no Spotify for my wife then ;)

**Comment by ejurgensen** [comment] 2020-12-29 15:44
I don't think libspotify is available for macOS, so even if you get the build to work it would be without Spotify.

Building for MacOS is somewhat complicated. The recipe that Github Actions uses is this one: https://github.com/ejurgensen/forked-daapd/blob/master/.github/workflows/macos.yml

Note that if you build from the release tar-ball you don't need antlr3 and gperf.

**Comment by kimme1024** [comment] 2020-12-29 16:09
Lol. If I’d known that before I wouldn’t have wasted my time :)
Anyways... I give up. Thanks for trying!
