### ISSUE TITLE
Quirky starting play with Hyperfine Remote

### ISSUE THREAD

**Issue by caesarsamsi** [ejurgensen/forked-daapd#423] opened 2017-09-30 18:46 UTC
I have v 25.0 compiled binaries in Raspberry Pi 2 with Raspbian Stretch.
Forked-daapd looks to run fine from the log.

I am using Hyperfine's Remote For iTunes. I can successfully pair my Samsung Galaxy S4, the library is displayed, the audio device is selected.

Here's the quirkiness: 
1. From the Albums list, I select an Album.
2. From that specific Album I tap on one Song.
(BUG) 3. The Song does not look play (I see the triangle play button)
4. I back out to the Album and the Song looks to play (I see the pause button)
5. I press the pause button. The Song stops
(BUG) 6. I press the play button. The Song does not start again. No amount of fiddling back to the Album and forth will make the song start.
(BUG) 7. Selecting a new song does not start the new song, I have to go out to the Albums list, select the Album, select the new song and then it starts playing

I ditched the compiled binary and installed forked-daapd from your repository. The installation appears to work. The only difference I can think of I was using the .conf file from version 24.2 which binary I overwrote with version 25.

The lesson learned is use the .conf file from the same version.

Aaaaaarghhhh, I reinstalled and it's exhibiting the same bugs as before.

**Comment by ejurgensen** [comment] 2017-09-30 21:31
Tried to reproduce, could only do it with (3). It does seem like Hyperfine does not seem to properly get the current playstatus when in the list screen. However, start/stop and changing songs worked, so I couldn't reproduce 6 and 7.

If you want to see some digging you could try setting the log level to debug in the config and see if there are requests that don't arrive to forked-daapd, or don't get replied. Look for lines tagged "dacp".

I didn't quite follow the last part you wrote, but it is very unlikely that the conf file has anything to say in this. Also, v24.2 and v25.0 are pretty much the same when it comes to Remote operation. Can't imagine it makes a difference if you build yourself or install my bin either.

**Comment by ejurgensen** [comment] 2017-10-20 20:38
Ok, I think I found and fixed bug 3. It was a bug in forked-daapd, and it looks like it has been there for 8 years, so about time it got squashed.

I can't say if bug 6 and 7 are also fixed by my change, since I have not been able to reproduce them. It would be great if you would check it out.

**Comment by caesarsamsi** [comment] 2017-10-21 03:29
Of course, where do we get the binary?


Sent from my Galaxy Tab® E
-------- Original message --------From: ejurgensen <notifications@github.com> Date: 10/20/17  1:38 PM  (GMT-08:00) To: ejurgensen/forked-daapd <forked-daapd@noreply.github.com> Cc: caesarsamsi <cmsamsi@hotmail.com>, Author <author@noreply.github.com> Subject: Re: [ejurgensen/forked-daapd] Quirky starting play with Hyperfine Remote (#423) 

Ok, I think I found and fixed bug 3. It was a bug in forked-daapd, and it looks like it has been there for 8 years, so about time it got squashed.
I can't say if bug 6 and 7 are also fixed by my change, since I have not been able to reproduce them. It would be great if you would check it out.
—

You are receiving this because you authored the thread.

Reply to this email directly, 
view it on GitHub, or 
mute the thread.






{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ejurgensen/forked-daapd","title":"ejurgensen/forked-daapd","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ejurgensen/forked-daapd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ejurgensen in #423: Ok, I think I found and fixed bug 3. It was a bug in forked-daapd, and it looks like it has been there for 8 years, so about time it got squashed.\r\n\r\nI can't say if bug 6 and 7 are also fixed by my change, since I have not been able to reproduce them. It would be great if you would check it out."}],"action":{"name":"View Issue","url":"https://github.com/ejurgensen/forked-daapd/issues/423#issuecomment-338316577"}}}

**Comment by ejurgensen** [comment] 2017-10-21 11:39
[Here's a binary for Stretch](http://www.gyfgafguf.dk/temp/forked-daapd_25.0.64~rc8-2_armhf.deb).

Install it with "sudo dpkg -i forked-daapd_25.0.64~rc8-2_armhf.deb".

**Comment by caesarsamsi** [comment] 2017-10-21 22:04
It works! I paired successfully with Remote for iTunes and the song started as soon as tapped on it.

Thank you!

On Oct 21, 2017, at 4:39 AM, ejurgensen <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's a binary for Stretch<https://nam01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gyfgafguf.dk%2Ftemp%2Fforked-daapd_25.0.64%257Erc8-2_armhf.deb&data=02%7C01%7Ccmsamsi%40hotmail.com%7C3f7abba124114955477208d518785ba0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636441827556139177&sdata=iwTT18ZlrGyZi31gS8e2oJDsHk1ChIpWomUm4E4FDc0%3D&reserved=0>.

Install it with "sudo dpkg -i forked-daapd_25.0.64~rc8-2_armhf.deb".

**Comment by caesarsamsi** [comment] 2017-10-22 17:25
Well, not sure what happened .. it took a while to list Albums, and a while to list songs in the album.

I rebooted, restarted. It was still slow.

I reinstalled the package. It was still slow, but at least I could still and tap a song but it would take about 5 seconds before it started playing.

On Oct 21, 2017, at 3:03 PM, Caesar Samsi <cmsamsi@hotmail.com<mailto:cmsamsi@hotmail.com>> wrote:

It works! I paired successfully with Remote for iTunes and the song started as soon as tapped on it.

Thank you!

On Oct 21, 2017, at 4:39 AM, ejurgensen <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's a binary for Stretch<https://nam01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gyfgafguf.dk%2Ftemp%2Fforked-daapd_25.0.64%257Erc8-2_armhf.deb&data=02%7C01%7Ccmsamsi%40hotmail.com%7C3f7abba124114955477208d518785ba0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636441827556139177&sdata=iwTT18ZlrGyZi31gS8e2oJDsHk1ChIpWomUm4E4FDc0%3D&reserved=0>.

Install it with "sudo dpkg -i forked-daapd_25.0.64~rc8-2_armhf.deb".

**Comment by caesarsamsi** [comment] 2017-10-22 22:41
Also takes a long time from tapping an artist to see the album list.

On Oct 22, 2017, at 10:25 AM, Caesar Samsi <cmsamsi@hotmail.com<mailto:cmsamsi@hotmail.com>> wrote:

Well, not sure what happened .. it took a while to list Albums, and a while to list songs in the album.

I rebooted, restarted. It was still slow.

I reinstalled the package. It was still slow, but at least I could still and tap a song but it would take about 5 seconds before it started playing.

On Oct 21, 2017, at 3:03 PM, Caesar Samsi <cmsamsi@hotmail.com<mailto:cmsamsi@hotmail.com>> wrote:

It works! I paired successfully with Remote for iTunes and the song started as soon as tapped on it.

Thank you!

On Oct 21, 2017, at 4:39 AM, ejurgensen <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's a binary for Stretch<https://nam01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gyfgafguf.dk%2Ftemp%2Fforked-daapd_25.0.64%257Erc8-2_armhf.deb&data=02%7C01%7Ccmsamsi%40hotmail.com%7C3f7abba124114955477208d518785ba0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636441827556139177&sdata=iwTT18ZlrGyZi31gS8e2oJDsHk1ChIpWomUm4E4FDc0%3D&reserved=0>.

Install it with "sudo dpkg -i forked-daapd_25.0.64~rc8-2_armhf.deb".

**Comment by ejurgensen** [comment] 2017-10-24 16:29
Can't reproduce the slowness with my Android. Could you set the log level to debug, and then grep the log file for "DAAP request"? This should show the exact queries that Hyperfine is making, as well as the amount of milliseconds it takes to process the request.

BTW, it would be good if you could edit your posts above and remove the cruft.

**Comment by caesarsamsi** [comment] 2017-10-28 01:23
Hi,

Trying to re-pair using my phone and Hyperfine’s remote … this is with your test build.

This worked before with this Pi (I imaged it once it worked).

Thank you, Caesar.

I get:

pi@airplay 2017-10-27  6:16 PM:~ $ sudo pairinghelper.sh
This script will help you pair Remote with forked-daapd
Please verify that these paths are correct:
  Log file: '/var/log/forked-daapd.log'
  Library:  '/media/Music'
Confirm? [Y/n]
Please start the pairing process in Remote by selecting Add library
Press ENTER when ready...
Looking in /var/log/forked-daapd.log for Remote announcement...found
Ready to pair Remote 'Remote for iTunes', please enter PIN: 1239
Writing pair.remote to /media/Music...
Waiting for pairing to complete (up to 20 secs)...
Pairing file pair.remote read, removing it
Pairing appears to have failed... check /media/Music/pair.remote for details


The log shows:
[2017-10-27 18:17:25] [  LOG]   remote: Discovered remote 'Remote for iTunes' (id 4233525334849636646966451397885847519651) at 192.168.0.32:62811, paircode 2528682659225127
[2017-10-27 18:17:41] [  LOG]   remote: Kickoff pairing with pin '1239'
[2017-10-27 18:18:26] [  LOG]   remote: Pairing failed with Remote 4233525334849636646966451397885847519651/Remote for iTunes, HTTP response code 0

The pair.remote file does not exist anymore (of course, since it was removed).

**Comment by caesarsamsi** [comment] 2017-10-28 01:38
This time it says No remote known ...

[2017-10-27 18:36:01] [  LOG]   remote: Discovered remote 'Remote for iTunes' (id 5183383841661638634363942596755547186416) at 192.168.0.32:1024, paircode 1592267548454824
[2017-10-27 18:36:28] [  LOG]   remote: Kickoff pairing with pin '4580'
[2017-10-27 18:36:28] [  LOG]   remote: No remote known from mDNS, ignoring
[2017-10-27 18:36:53] [  LOG]   remote: Pairing failed with Remote 5183383841661638634363942596755547186416/Remote for iTunes, HTTP response code 0

**Comment by caesarsamsi** [comment] 2017-10-28 01:52
loglevel set to debug.

[2017-10-27 18:49:25] [DEBUG]     mdns: Avahi Browser: NEW service '3195676931466553659878546754123568525681' type '_touch-remote._tcp' proto 0
[2017-10-27 18:49:25] [DEBUG]     mdns: Avahi Resolver: resolved service '3195676931466553659878546754123568525681' type '_touch-remote._tcp' proto 0, host 192-168-0-32.local
[2017-10-27 18:49:25] [DEBUG]     mdns: Avahi Record Browser (192-168-0-32.local, proto 0): NEW record 192.168.0.32 for service type '_touch-remote._tcp'
[2017-10-27 18:49:25] [  LOG]   remote: Discovered remote 'Remote for iTunes' (id 3195676931466553659878546754123568525681) at 192.168.0.32:1024, paircode 9929475159633192
[2017-10-27 18:49:25] [DEBUG]   remote: Remote id 3195676931466553659878546754123568525681 not known, adding
[2017-10-27 18:49:38] [DEBUG]       db: Running query 'SELECT * FROM inotify WHERE wd = 1;'
[2017-10-27 18:49:38] [DEBUG]     scan: File event: 0x100, cookie 0x0, wd 1
[2017-10-27 18:49:38] [DEBUG]     scan: File created: /media/Music/pair.remote
[2017-10-27 18:49:38] [DEBUG]       db: Running query 'SELECT * FROM inotify WHERE wd = 1;'
[2017-10-27 18:49:38] [DEBUG]     scan: File event: 0x8, cookie 0x0, wd 1
[2017-10-27 18:49:38] [DEBUG]     scan: File closed: /media/Music/pair.remote
[2017-10-27 18:49:38] [DEBUG]       db: Running query 'SELECT d.id FROM directories d WHERE d.virtual_path = '/file:/media/Music';'
[2017-10-27 18:49:38] [  LOG]   remote: Kickoff pairing with pin '5218'
[2017-10-27 18:49:38] [DEBUG]   remote: Adding pin to remote 'Remote for iTunes'
[2017-10-27 18:49:38] [DEBUG]   remote: Pairing hash for 3195676931466553659878546754123568525681/Remote for iTunes: 1BCF49A374437CF2EAF6A8E87ECCF9DB
[2017-10-27 18:49:38] [DEBUG]   remote: Pairing requested to /pair?pairingcode=1BCF49A374437CF2EAF6A8E87ECCF9DB&servicename=339EB22A0779C53F
[2017-10-27 18:49:38] [DEBUG]       db: Running query 'SELECT * FROM inotify WHERE wd = 1;'
[2017-10-27 18:49:38] [DEBUG]     scan: File event: 0x200, cookie 0x0, wd 1
[2017-10-27 18:49:38] [DEBUG]     scan: File deleted: /media/Music/pair.remote
[2017-10-27 18:49:38] [DEBUG]       db: Running query 'DELETE FROM files WHERE path = '/media/Music/pair.remote';'
[2017-10-27 18:49:38] [DEBUG]       db: Running query 'SELECT p.id FROM playlists p WHERE p.path = '/media/Music/pair.remote';'
[2017-10-27 18:49:38] [ INFO]       db: No matching row found for query: SELECT p.id FROM playlists p WHERE p.path = '/media/Music/pair.remote';
[2017-10-27 18:49:38] [DEBUG]    cache: Running query 'DELETE FROM artwork WHERE filepath = '/media/Music/pair.remote';'
[2017-10-27 18:49:38] [DEBUG]    cache: Deleted 0 rows
[2017-10-27 18:50:23] [  LOG]   remote: Pairing failed with Remote 3195676931466553659878546754123568525681/Remote for iTunes, HTTP response code 0
[2017-10-27 18:50:38] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND f.data_kind = 3;'
[2017-10-27 18:50:38] [DEBUG]       db: Starting query 'SELECT f.* FROM files f WHERE f.disabled = 0 AND f.data_kind = 3  ;'
[2017-10-27 18:50:38] [DEBUG]       db: End of query results
[2017-10-27 18:50:48] [  LOG]    cache: Beginning DAAP cache update
[2017-10-27 18:50:48] [DEBUG]     daap: Building reply for DAAP request: /databases/1/items?delta=0&type=music&meta=all
[2017-10-27 18:50:48] [DEBUG]     daap: Fetching song list for playlist -1
[2017-10-27 18:50:48] [DEBUG]     daap: Asking for 1 meta tags
[2017-10-27 18:50:48] [ WARN]     daap: Could not find requested meta field 'all'
[2017-10-27 18:50:48] [DEBUG]     daap: Found 0 meta tags
[2017-10-27 18:50:48] [DEBUG]     daap: SQL filter w/client mod: (f.data_kind = 0)
[2017-10-27 18:50:48] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND (f.data_kind = 0);'
[2017-10-27 18:50:48] [DEBUG]       db: Starting query 'SELECT f.* FROM files f WHERE f.disabled = 0 AND (f.data_kind = 0)  ;'

**Comment by ejurgensen** [comment] 2017-10-28 07:49
The error is basically the same in all three attempts, the remote is not replying to the pairing request:
> Pairing failed with Remote 3195676931466553659878546754123568525681/Remote for iTunes, HTTP response code 0

See the README for troubleshooting: https://github.com/ejurgensen/forked-daapd#no-response-from-remote-possibly-a-network-issue

BTW With the build I made you can use the web interface for pairing - but that won't solve the problem.

**Comment by caesarsamsi** [comment] 2017-10-29 17:57
I noticed you have the test build up as production.

May I have the binary that was production before?

In that version TunesRemote still worked.

It does not work with the version up there now.

At least with the previous version, TunesRemote works.

The new version doesn’t work with remote.

Thank you, Caesar.

**Comment by ejurgensen** [comment] 2017-10-29 18:36
Not sure what versions you are referring to? If you by production [mean this one](https://www.raspberrypi.org/forums/viewtopic.php?t=49928) then I haven't changed that in a while. What is the previous version you are referring to? And what is the "test build" - if it is the one above then I can say that it is not anywhere else.

**Comment by caesarsamsi** [comment] 2017-10-29 19:24
Ah, I managed to sort pairing out. There was a cross subnet LAN connection that I had to remove. Remote for iTunes (Hyperfine) works well now.

The slowness persists. I turned on the debug log and can see the very first time Remote for iTunes run, it’s plenty fast going from:
- Artist -> Album -> Song
- Album -> Song

Here’s the last few lines from the log, it just hangs there. I can tap on Albums, Artists, Genres but there’s no response.

I can only make it work once, right after forked-daad is restarted.

[2017-10-29 12:20:55] [DEBUG]     dacp: DACP request: /ctrl-int/1/playqueue-contents?span=50&session-id=2119435558
[2017-10-29 12:20:55] [DEBUG]     dacp: Fetching playqueue contents
[2017-10-29 12:20:55] [DEBUG]   player: Player status: stopped
[2017-10-29 12:20:55] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2017-10-29 12:20:55] [DEBUG]       db: Starting enum 'SELECT * FROM queue WHERE 1=1 ORDER BY pos ASC;'
[2017-10-29 12:20:55] [DEBUG]       db: End of queue enum results
[2017-10-29 12:20:55] [DEBUG]       db: Running query 'END TRANSACTION;'
[2017-10-29 12:20:55] [DEBUG]     dacp: DACP request: /ctrl-int/1/playstatusupdate?revision-number=7&session-id=2119435558

**Comment by caesarsamsi** [comment] 2017-10-29 19:25
and also right after I launch Remote for iTunes.

**Comment by caesarsamsi** [comment] 2017-10-29 20:26
Using forked-daapd_25.0.64-rc8-2_armhf.deb

Repro steps:

  1.  kill Remote for iTunes on android phone
  2.  sudo service forked-daapd stop
  3.  sudo rm /var/log/forked-daapd.log
  4.  sudo service forked-daapd start
  5.  sudo tail -f -n 20 /var/log/forked-daapd
  6.  start Remote for iTunes on android phone
  7.  android phone connecting … for a long time not doing anything
  8.  click “Setting” on android phone
  9.  Albums displayed on android phone (very quickly)
  10. Tap topmost album
  11. Album shows
  12. Tap on topmost song … 20 seconds not doing anything
  13. Song plays, no sound from speaker
  14. Tap on song playing to get to the speaker setting
  15. Volume shows 0
  16. Tap on speaker
  17. A list of speakers show
  18. I select my Master Bedroom
  19. I tap the song again (speaker selection should be saved)
  20. Tap on speaker, previous selection not saved
  21. Go back to album
  22. Select another song random … for a long time not doing anything
  23. Song plays, no sound from speaker
  24. Select speaker, nothing is selected
  25. Go back to Albums
  26. Select an album a bit slow
  27. Select a song … for a long time not doing anything
  28. Song plays no sound from speaker
  29. Change speaker, no sound from speaker

I tried a few more times with no success.

**Comment by ejurgensen** [comment] 2017-10-29 21:19
Yes, I can reproduce. What Hyperfine is doing looks a bit odd to me: It makes a request that according to DACP specs actually should hang (it's used to push play status changes from the server), but seems to expect an immediate return. I will look more into it and try to figure out why it is behaving like that.

**Comment by ejurgensen** [comment] 2017-10-30 20:02
I reckon I found the problem and have it fixed. My first fix wasn't quite right, it was not returning a certain "revision number" as it should have. Here is another build for you try: [forked-daapd_25.0.64~rc15-2_armhf.deb](forked-daapd_25.0.64~rc15-2_armhf.deb)

Note that this build also includes a bunch of other changes that I have done, and which I am currently testing. So if you observe something that you think is broken it might be from that. Then please let me know.

**Comment by caesarsamsi** [comment] 2017-10-30 20:43
Thank you but it doesn't include a link ...

**Comment by ejurgensen** [comment] 2017-10-30 21:22
Here it is http://www.gyfgafguf.dk/temp/forked-daapd_25.0.64~rc15-2_armhf.deb

**Comment by caesarsamsi** [comment] 2017-11-02 16:47
Hey, sorry, not yet. I've been busy this week. One nice new its that remote for iTunes is working now once the firewall rule to allow source port 6002 was in place. Also I removed the cross subnet routing.
I'll try this weekend, if not today after work.


Sent from my T-Mobile 4G LTE Device








{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ejurgensen/forked-daapd","title":"ejurgensen/forked-daapd","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ejurgensen/forked-daapd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ejurgensen in #423: Have you had the opportunity to test the new version? I'm very interested in knowing if it now works with your Hyperfine Remote."}],"action":{"name":"View Issue","url":"https://github.com/ejurgensen/forked-daapd/issues/423#issuecomment-341474218"}}}

**Comment by caesarsamsi** [comment] 2017-11-04 19:44
Hi,

Install failed, looks like I need to update.

Trying again.

pi@airplay 2017-11-04 12:43 PM:~/Downloads $ sudo dpkg -i forked-daapd_25.0.64-rc15-2_armhf.deb
(Reading database ... 124825 files and directories currently installed.)
Preparing to unpack forked-daapd_25.0.64-rc15-2_armhf.deb ...
Unpacking forked-daapd (25.0.64~rc15-2) over (25.0.64~rc15-2) ...
dpkg: dependency problems prevent configuration of forked-daapd:
 forked-daapd depends on libavfilter6 (>= 7:3.2.8) | libavfilter-extra6 (>= 7:3.2.8); however:
  Version of libavfilter6:armhf on system is 7:3.2.5-1.
  Package libavfilter-extra6 is not installed.
 forked-daapd depends on libavformat57 (>= 7:3.2.8); however:
  Version of libavformat57:armhf on system is 7:3.2.5-1.
 forked-daapd depends on libswscale4 (>= 7:3.2.8); however:
  Version of libswscale4:armhf on system is 7:3.2.5-1.

dpkg: error processing package forked-daapd (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (232-25+deb9u1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 forked-daapd

**Comment by caesarsamsi** [comment] 2017-11-04 19:56
Fixed dependencies for a minute, it installed.

**Comment by caesarsamsi** [comment] 2017-11-04 20:03
Works awesome, very fast going from artist to albums to songs. also from albums to songs. also genres.

Songs play within 1 second of tapping.

This build is a keeper!

**Comment by caesarsamsi** [comment] 2017-11-04 20:26
So far so good. Some slowness getting a song to start, at most 5 seconds, but most within 1-2 seconds.

Album-Songs-Song, Artist-Album-Song, Genres-Album-Song are all very fast!

Thank you, Caesar.

**Comment by caesarsamsi** [comment] 2017-11-04 20:33
Just FYI, TunesRemote+ doesn’t pair now.

[2017-11-04 13:22:02] [  LOG]   remote: Discovered remote 'SM-G930T' (id ffffffff-bf61-a5a3-ffff-fff
fe84867b3) at 192.168.1.67:1024, paircode 0000000000000001
[2017-11-04 13:22:02] [DEBUG]   remote: Remote id ffffffff-bf61-a5a3-ffff-ffffe84867b3 not known, ad
ding
[2017-11-04 13:23:22] [DEBUG]     daap: DAAP request: /login?pairing-guid=0xnull
[2017-11-04 13:23:22] [DEBUG]       db: Running query 'SELECT p.* FROM pairings p WHERE p.guid = 'nu
ll';'
[2017-11-04 13:23:22] [ INFO]       db: Pairing GUID null not found
[2017-11-04 13:23:22] [  LOG]     daap: Login attempt with invalid pairing-guid: 0xnull
[2017-11-04 13:23:22] [DEBUG]     daap: DAAP request handled in 2 milliseconds
[2017-11-04 13:23:23] [DEBUG]     mdns: Avahi Browser: NEW service 'ffffffff-bf61-a5a3-ffff-ffffe848
67b3 (2)' type '_touch-remote._tcp' proto 0
[2017-11-04 13:23:23] [DEBUG]     mdns: Avahi Resolver: resolved service 'ffffffff-bf61-a5a3-ffff-ff
ffe84867b3 (2)' type '_touch-remote._tcp' proto 0, host tunesremote.local
[2017-11-04 13:23:23] [DEBUG]     mdns: Avahi Record Browser (tunesremote.local, proto 0): NEW recor
d 192.168.1.67 for service type '_touch-remote._tcp'
[2017-11-04 13:23:23] [  LOG]   remote: Discovered remote 'SM-G930T' (id ffffffff-bf61-a5a3-ffff-fff
fe84867b3 (2)) at 192.168.1.67:1024, paircode 0000000000000001
[2017-11-04 13:23:23] [DEBUG]   remote: Remote id ffffffff-bf61-a5a3-ffff-ffffe84867b3 (2) not known
, adding
[2017-11-04 13:23:23] [DEBUG]   remote: Removing existing remote with id ffffffff-bf61-a5a3-ffff-fff
fe84867b3
[2017-11-04 13:23:28] [DEBUG]     mdns: Avahi Browser: REMOVE service 'ffffffff-bf61-a5a3-ffff-ffffe
84867b3' type '_touch-remote._tcp' proto 0
[2017-11-04 13:23:28] [ WARN]   remote: Remote ffffffff-bf61-a5a3-ffff-ffffe84867b3 not found in lis
t
[2017-11-04 13:25:23] [DEBUG]       db: Running query 'SELECT * FROM inotify WHERE wd = 1;'
[2017-11-04 13:25:23] [DEBUG]     scan: File event: 0x100, cookie 0x0, wd 1
[2017-11-04 13:25:23] [DEBUG]     scan: File created: /media/Music/pair.remote
[2017-11-04 13:25:23] [DEBUG]       db: Running query 'SELECT * FROM inotify WHERE wd = 1;'
[2017-11-04 13:25:23] [DEBUG]     scan: File event: 0x8, cookie 0x0, wd 1
[2017-11-04 13:25:23] [DEBUG]     scan: File closed: /media/Music/pair.remote
[2017-11-04 13:25:23] [DEBUG]       db: Running query 'SELECT d.id FROM directories d WHERE d.virtua
l_path = '/file:/media/Music';'
[2017-11-04 13:25:23] [  LOG]   remote: Kickoff pairing with pin '5309'
[2017-11-04 13:25:23] [DEBUG]   remote: Adding pin to remote 'SM-G930T'
[2017-11-04 13:25:23] [DEBUG]   remote: Pairing hash for ffffffff-bf61-a5a3-ffff-ffffe84867b3 (2)/SM-G930T: 1742231EBDB31CE4CE3EAB0E74DCF255
[2017-11-04 13:25:23] [DEBUG]   remote: Pairing requested to /pair?pairingcode=1742231EBDB31CE4CE3EAB0E74DCF255&servicename=339EB22A0779C53F
[2017-11-04 13:25:23] [DEBUG]       db: Running query 'SELECT * FROM inotify WHERE wd = 1;'
[2017-11-04 13:25:23] [DEBUG]     scan: File event: 0x200, cookie 0x0, wd 1
[2017-11-04 13:25:23] [DEBUG]     scan: File deleted: /media/Music/pair.remote
[2017-11-04 13:25:23] [DEBUG]       db: Running query 'DELETE FROM files WHERE path = '/media/Music/pair.remote';'
[2017-11-04 13:25:23] [DEBUG]       db: Running query 'SELECT p.id FROM playlists p WHERE p.path = '/media/Music/pair.remote';'
[2017-11-04 13:25:23] [ INFO]       db: No matching row found for query: SELECT p.id FROM playlists p WHERE p.path = '/media/Music/pair.remote';
[2017-11-04 13:25:23] [DEBUG]    cache: Running query 'DELETE FROM artwork WHERE filepath = '/media/Music/pair.remote';'
[2017-11-04 13:25:23] [DEBUG]    cache: Deleted 0 rows
[2017-11-04 13:26:08] [  LOG]   remote: Pairing failed with 'SM-G930T' (192.168.1.67:1024), no reply from Remote

**Comment by ejurgensen** [comment] 2017-11-04 20:38
Great, I will close the issue then.

I see TunesRemote+ gives a "/login?pairing-guid=0xnull", which is not really ok. You can, however, get around it with the new config setting which is called "promiscuous_mode". I think it is in the test build you have. If you enable that you should be able to connect anyway.

Dunno if there is anything to do about song start. Maybe there are some Airplay tricks, but I don't know them.

**Closed by ejurgensen** 2017-11-04 20:38 UTC
Labels: bug

**Comment by alirezadigi** [comment] 2023-11-28 21:11
@caesarsamsi how did you resolve dependencies?? i get this error

```
dpkg: dependency problems prevent configuration of owntone:
 owntone depends on libavcodec59 (>= 7:5.0); however:
  Package libavcodec59 is not installed.
 owntone depends on libavfilter8 (>= 7:5.0); however:
  Package libavfilter8 is not installed.
 owntone depends on libavformat59 (>= 7:5.0); however:
  Package libavformat59 is not installed.
 owntone depends on libavutil57 (>= 7:5.1); however:
  Package libavutil57 is not installed.
 owntone depends on libgcrypt20 (>= 1.10.0); however:
  Version of libgcrypt20:amd64 on system is 1.9.4-3ubuntu3.
 owntone depends on libgnutls30 (>= 3.7.5); however:
  Version of libgnutls30:amd64 on system is 3.7.3-4ubuntu1.2.
 owntone depends on libmxml1 (>= 3.3.1); however:
  Version of libmxml1:amd64 on system is 3.3-1.
 owntone depends on libwebsockets17 (>= 2.4.1); however:
  Package libwebsockets17 is not installed.
```

**Comment by ejurgensen** [comment] 2023-11-28 22:10
That error is most likely because you are trying to install a deb on distribution it wasn't made for
