### ISSUE TITLE
[  LOG]   laudio: Error initializing Pulseaudio: Connection refused

### ISSUE THREAD

**Issue by marioscube** [ejurgensen/forked-daapd#286] opened 2016-08-29 11:53 UTC
I installed the latest version of forked-daapd, with support for pulse audio, from github.

I installed it on Debian Jessie (uname -a: Linux Atom330 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux).

All required tools and libraries (including lib pulse-dev) are installed.

I build with ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-pulseaudio

In /var/log/forked-daadp.log: 
[2016-08-29 13:33:17] [DEBUG]   laudio: Pulseaudio context state CB
[2016-08-29 13:33:17] [DEBUG]   laudio: CTX START
[2016-08-29 13:33:17] [DEBUG]   laudio: Pulseaudio context state CB
[2016-08-29 13:33:17] [DEBUG]   laudio: CTX FAIL
[2016-08-29 13:33:17] [  LOG]   laudio: Error initializing Pulseaudio: Connection refused

In /etc/forked-daapd.conf I have:
audio {
	# Name - used in the speaker list in Remote
	nickname = "Atom330"
	# Type of the output (alsa, pulseaudio or dummy)
        type = "pulseaudio"
        # card = "default"
        # mixer = ""
	offset = 0
}

Pulseaudio works with VLC. To clarify, I have tried with a bluetooth headphone (Bluez 5 is installed) and with an (ancient) Griffin iMic USB audio adapter. Both are recognised as output devices in PulseAudio Volume Control (GUI).

Did I do something wrong or did I miss a setting?

**Comment by ejurgensen** [comment] 2016-08-29 13:22
You are quick to try this :-)

You didn't miss anything, I have seen the same error. Think it comes when forked-daapd runs as root, but haven't gotten to the bottom of it. What user do you run forked-daapd as?

**Comment by marioscube** [comment] 2016-08-29 13:43
root ;-)

What is, in your opinion, the best way to set another user ("daapd"?) as forked-daapd user? Maybe that's the way to go?

**Comment by ejurgensen** [comment] 2016-08-29 14:23
In some situations I think root is ok, but that is just my personal opinion. The most correct solution is probably "daapd" like the Debian package does:

"adduser --quiet --system --no-create-home --home /var/cache/forked-daapd daapd"

I'm still working on Pulseaudio. If you encounter further issues let me know.

**Comment by marioscube** [comment] 2016-08-29 16:38
Running as root on my test server does not bother me. But maybe running as daapd is more Debian compliant.

Now running as daapd:root (?) I still have the same issue with Pulseaudio.
Forked-daapd either does not recognize Pulse Audio or does not start it.

**Comment by ejurgensen** [comment] 2016-08-29 20:53
Hm, yes, I am trying to get a better understanding of how Pulseaudio autostarts its daemon. As a work around until I find a better solution, you can probably get going by again running forked-daapd as root, and manually starting the Pulseaudio daemon with sudo (before you start forked-daapd): "sudo pulseaudio --start".

**Comment by marioscube** [comment] 2016-08-29 23:21
Your suggestion did not work for me. I still get the same error in the log file.
I even recompiled the with the latest github source.

It won't work even when I start forked-daapd with the default user (so not daapd or root).

Just tell me if I can do some testing ;-)
It's all for a good cause!

**Comment by ejurgensen** [comment] 2016-09-01 20:58
After much googling I ended up [asking the Pulseaudio folks](https://lists.freedesktop.org/archives/pulseaudio-discuss/2016-August/026824.html) what the proper way of starting Pulseaudio in this scenario would be. The gist of it is this:

1. Make a pulseaudio.service file. There is no official file, but there are plenty of unofficial ones out there. [I used something like this](https://gist.github.com/awidegreen/6003640/revisions).
2. Place it in /etc/systemd/system and run "sudo systemctl daemon-reload"
3. Stop any running instances of Pulseaudio, and then run "sudo systemctl start pulseaudio"
4. Add whatever user that forked-daapd is running as (even if it is root) to the "pulse-access" group
5. Run/restart forked-daapd

**Comment by marioscube** [comment] 2016-09-01 23:02
What I did [Debian Jessie xfce from terminal (ssh) as root]:
1 - made pulseaudio.service file, used your "recommended" example.
2 - ran systemctl daemon-reload
3 - added user daapd (I run forked-daapd as user daapd) to group pulseaudio-access
4 - reboot
5 - stop forked-daapd (sytemctl stop forked-daapd)
6 - start pulseaudio daemon (systemctl start forked-daapd) (stop or pulseaudio --k has no effect) started with some warnings ..... 
7 - start forked-daapd (systemctl start forked-daapd)
8 - check /var/log/forkedp-daadp >> laudio: Error initializing Pulseaudio: Access denied
9 - check pulseaudio status (systemctl status pulseaudio) >> [pulseaudio] protocol-native.c: Denied access to client with invalid authorization data.  

So, no luck!

Does it work for you? What did I do different?

(I'm starting to understand why people on the www dislike pulseaudio. 
If only bluetooth would work with Alsa. It used to, sort of, but only with the previous version of Bluez in the previous version of Debian=wheezy). :-(

**Comment by ejurgensen** [comment] 2016-09-02 07:51
Yes, it worked for me. I did get the "Access denied" error at one point, but that was because the user was not in the "pulse-access" group. You wrote "pulseaudio-access", but I suppose you did actually add to "pulse-access"? You could also try adding the user to "audio", but not sure if that is actually required.

I tested with root, not daapd, but that shouldn't be the cause.

Yes, I agree that this is pretty cumbersome for something as basic as outputting to a soundcard.

**Comment by marioscube** [comment] 2016-09-02 12:10
The output of: 
   groups daapd
is:  daapd : daapd audio pulse-access

  members pulse-access
is:  daapd

Something is not going as expected for me. Never mind. I will try with another distro this weekend and see if my luck might change.

**Comment by ejurgensen** [comment] 2016-09-02 18:01
Very good investigation! And glad you found out, without changing distro, which wouldn't have helped, I suppose.

I would never have had guessed that having a password would have significance, but your conclusion is consistent with what I have observed. I don't understand why Pulseaudio does this.

**Comment by ejurgensen** [comment] 2016-09-02 19:46
Looking a bit more into it, I don't think it is the password the matters. What matters is that the "daapd" user has a valid home directory (so "/var/cache/forked-daapd") and has write access to it. This is because Pulseaudio needs to save some stuff in "~/.config/pulse". So in your case I think it was the chown that made the difference.

**Comment by marioscube** [comment] 2016-09-02 22:29
I would agree with you, however
1 - pulseaudio has writing rights in /var/cache/forked-daapd but does not actually write anything there
2 - the pulsaudio daemon is started by root. Pulsaudio writes it cookie in /root/.config/pulse.
3 - before I chown-ed /var/cache/forked-daapd I already tried chmod 777. This did not help.
4 - I tried with my default user (no member of pulse-access) and it worked (did not try both with or without chown, only with. And it worked.
5 - then I gave user daapd a passwd and chown-ed /var/cache/forked-daapd so the user could write to the databases. Permissions on the databases are:
-rw-r--r-- 1 daapd daapd 3716096 Sep  3 00:02 cache.db
-rw-r--r-- 1 daapd daapd  102400 Sep  3 00:01 songs3.db

The only thing I changed that "made it work" was adding a password to user daapd.

In order to let pulseaudio and forked-daapd recognize one another I do this:
1 - stop forked-daapd (service forked-daapd stop /or/ systemctl stop forked-daapd)
2 - start the  daemon (systemctl start pulseaudio)
3 - start forked-daapd (service forked-daapd start /or/ systemctl start forked-daapd)

To let other apps (VLC) use pulseaudio stop the daemon. VLC cannot be started as root so start it with another user. Pulsauadio will write it's cookie and some other stuff in /home/<user>/.config/pulse

To be 100% certain it all really works I still need to test with my bluetooth earphones/speaker.
Maybe this weekend.

**Comment by ejurgensen** [comment] 2016-09-19 20:19
I'm not sure what the conclusion from all this was. Did you get it working with Bluetooth?

I get the impression that running Pulseaudio in system mode gives other problems, so maybe it is better to just run it in a per-user manner, like it normally does? So let the forked-daapd user start it with "pulseaudio --start".

**Comment by marioscube** [comment] 2016-09-20 20:40
I never got pulseaudio in system mode to work with bluetooth.
One possible reason for not working is the desktop environment that captures pulseaudio (or bluetooth?) before I start pulsaudio in system mode (ven when I kill pulseaudio first).
To confirm this I have to reinstall Debian Jessie without a desktop environment. No problem, but I need to empty a HD first and I haven't done that yet (was testing so other things I did not want to interrupt). Maybe later this week.

I will also try pulsauadio with "pulseaudio --start" again. I can't-remember if I already tried tat or not.

**Comment by marioscube** [comment] 2016-09-23 21:16
Finally! I have got it all (Bluetooth) working, more or less like I intended it to.

What I wanted was running forked-daapd on a headless linux server with the possibility to listen to my music via a Bluetooth speaker or headset. Forked-daapd never was the problem. Neither were external or internal sound-cards. They all worked with pulseaudio in system mode. (I used system mode, not "pulseaudio --start".
Bluetooth refused to work (in Debian Jessie with bluez5) with forked-daapd. 

After a lot of "googling" it was clear that "module-bluetooth-discover" was not loaded although it should have been. (Strange)

To make it all working I use the following very simple shell script:
#!/bin/sh
service forked-daapd stop
killall pulseaudio
sleep 2
systemctl start pulseaudio
sleep 5
pactl load-module module-bluetooth-discover
sleep 2
service forked-daapd start
echo "Now connect bluetooth speaker/headset"

The sleep commands are (in my usecase) necessary because some commands seem to need some time to take effect. Without them I get errors. With a faster CPU this might not be necessary.

The Bluetooth speaker / headset can be paired and connected with bluetoothctl.
Music can be played with forked-daapd using my iPad as a remote.

[this issue can be closed]

**Comment by ejurgensen** [comment] 2016-09-26 19:43
Thank you for the update. From the feedback I have gotten, it seems that the main challenge with Pulseaudio is getting the setup right for forked-daapd and Bluetooth. Of course, I would prefer it to "just work", so now I have made a modification that at least should assure that Pulseaudio gets started as the forked-daapd user. This should mean that you don't need to run Pulseaudio in system mode, which isn't really recommended by the Pulseaudio docs either. I'm hoping it also means that you can do without the script.

So if you're up to it, it would be great if you would test current master-branch, and without Pulseaudio system mode or any of the other Pulseaudio customisations for forked-daapd you have made.

**Comment by marioscube** [comment] 2016-09-26 22:19
Ok. 
 - git clone forked-daadp
 - configure with --with-pulseaudio + make
 - reboot (Debian Jessie PC)

No luck. Forked-daapd does not start pulsaudio and pulsaaudio --start does not help.
But VLC also cannot connect to the bluetooth speaker. Bluetooth does not show in pavucontrol.

Tomorrow I will reinstall pulse audio, maybe something is wrong with my pulse audio setup? 

The method with system mode still works i]when I try ;-)  but thats not what we want.

**Comment by marioscube** [comment] 2016-09-27 13:57
I reinstalled pulsaudio (and tested with a soundcard, not yet bluetooth).
I did not do any additional editing of configuration files.

log file: [  LOG]   laudio: Error initializing Pulseaudio: Connection refused
forked-daapd status : pulseaudio[2021]: Daemon already running.
So i'm back to the original error!

Now pulseaudio system mode does not work anymore.

**Comment by ejurgensen** [comment] 2016-09-27 14:00
Ok, I will try with a fresh Debian Jessie VM tonight. What user do you have
forked-daapd running as?

2016-09-27 15:57 GMT+02:00 marioscube <notifications@github.com>:

**Comment by marioscube** [comment] 2016-09-27 14:07
daapd

I'm thinking to do the same (but not a VM. My test PC does not do vt-x.)

**Comment by marioscube** [comment] 2016-09-28 14:38
Today: 
 - using latest github version forked-daapd on original test setup
 - user = root
 - played 3 CD's (mp3/flac) without problem on a bluetooth speaker (iPad Remote)
 - as always some fiddling necessary to see Bluetooth Speaker in forked-daapd (stop/start and Bluetoothctl connect)

Todo:
 - try with user other than root

**Comment by ejurgensen** [comment] 2016-09-28 14:46
Yes, it seems that the current solution works ok for root, but not so well for non-root. I did a bunch of googling on the issue, and I couldn't find a good solution for non-root except for Pulseaudio system mode. It is a hassle to set up, and I really hoped to avoid that, but maybe it is just not possible.

**Comment by marioscube** [comment] 2016-09-28 15:00
Maybe it's because forked-daapd runs as a daemon?
Where do you specify GROUP in any config file if the user <> root? Just a thought......

The problems with Bluetooth / Pulseaudio are something else ....... grrrrr. ;-)

**Comment by ejurgensen** [comment] 2016-10-13 21:05
Closing, possible remaining issues with Pulseaudio seem to be outside of forked-daapd

**Closed by ejurgensen** 2016-10-13 21:05 UTC
