### ISSUE TITLE
Silent audio playing AirPlay devices with ipv6

### ISSUE THREAD

**Issue by loudnate** [ejurgensen/forked-daapd#498] opened 2018-02-25 02:11 UTC
Hello,

I'm unable to hear audio playing on my AirPlay devices (single output). Both devices indicate that audio is streaming, e.g. the Apple TV shows the metadata in the top-right when playback begins. 
Audio does play to the local source correctly when selected (Raspberry Pi 2, verified with headphones).

The log shows the following error message on repeat, but I don't believe it's related.
```
[2018-02-24 18:10:30] [  LOG]     raop: Control request from 2601:643:8500:df70:5415:9b9d:c070:a84f; not a RAOP client
[2018-02-24 18:10:30] [  LOG]     raop: Control request from 2601:643:8500:df70:5415:9b9d:c070:a84f; not a RAOP client
```

Thanks for your help.

**Comment by ejurgensen** [comment] 2018-02-25 09:03
Does it work if you disable ipv6 in forked-daapd's config?

Are both of the devices Apple TV's? Which version?

**Comment by loudnate** [comment] 2018-02-25 18:55
I upgraded to 26.0 (thanks!) but still have the same issue.
Disabling IPv6 (commenting out `ipv6 = yes`) had no effect either.

The Apple TV is a 4th generation running the 11.3 public beta.

**Comment by ejurgensen** [comment] 2018-02-25 19:13
Set the setting to ‘no’. Commenting out just selects the default which is
yes.
søn. 25. feb. 2018 kl. 19.55 skrev Nathan Racklyeft <
notifications@github.com>:

**Comment by loudnate** [comment] 2018-02-25 19:16
That worked. Thank you!

Is there anything I can help you diagnose?

**Comment by ejurgensen** [comment] 2018-02-25 22:59
Great if you would help with that! Let me get back to you with what I need.

**Comment by ejurgensen** [comment] 2018-02-26 17:44
Ok, here's what could help: In the config, set the log level to "info" and again set ipv6 to "yes". Restart and try to start playback, which I assume won't work again. Then post the log file as an attachment here.

**Comment by loudnate** [comment] 2018-03-03 17:14
[ipv6-no-audio-apple-tv.log](https://github.com/ejurgensen/forked-daapd/files/1777695/ipv6-no-audio-apple-tv.log)

**Comment by loudnate** [comment] 2018-03-03 17:16
[2018-03-03 09:10:57] # started playing
[2018-03-03 09:11:00] # Switched to Apple TV output. Metadata appeared on screen, but audio was silent

**Comment by ejurgensen** [comment] 2018-03-03 19:04
Thanks. It looks like your ATV has two ipv6 addresses:
```
2601:643:8500:df70:cf3:6191:e15c:cd38
2601:643:8500:df70:f42d:cec9:bbd7:658a
```
It is announcing the former, but making connections from the latter, which forked-daapd isn't prepared for.

Can you confirm (e.g. on your router) that the ATV actually has these two addresses? Is the ATV both wired and on wifi? Or can you think of other reasons why it would be having two addresses?

**Comment by Iznohak** [comment] 2018-06-22 16:41
IPv6 client on Windows and mac/i/tvOS use 2 routable IPv6 addresses to an interface: one auto-configured based on the MAC address of the interface, which is fixed, and another one not based on the MAC address using some random bits, which is temporary and changes over time. Typically when acting as a client the temporary address is used, to mask the MAC address, and when acting as a server, the fixed address is used. See [https://en.wikipedia.org/wiki/IPv6_address#Temporary_addresses](). Linux doesn't seem to assign temporary addresses.

For example on my Windows 10 machine (with some parts changed to protect privacy). Notice the IPv6 fixed address and the IPv6 link-local address have identical second half corresponding to the MAC address, while the IPv6 temporary address has identical first half corresponding to routable prefix, but different (randomized) second half to hide real MAC address.
```
C:\>ipconfig

Windows IP Configuration


Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : home
   IPv6 Address. . . . . . . . . . . : 2a01:5678:910:700:34dc:8abd:44ec:b15a
   Temporary IPv6 Address. . . . . . : 2a01:5678:910:700:4d5:44ce:7fe2:8893
   Link-local IPv6 Address . . . . . : fe80::34dc:8abd:44ec:b15a%10
   IPv4 Address. . . . . . . . . . . : 192.168.1.107
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : fe80::ab26:6cfd:fe36:4e26%10
                                       192.168.1.1

```

**Comment by ejurgensen** [comment] 2018-06-22 17:24
Yes, makes sense. I'm not sure how to handle this because forked-daapd uses the source address to identify the session. Basically it works like this:

1. forked-daapd opens a connection to the announced address (A) and sets up a session
2. from address B the device opens a control connection back to forked-daapd

The control connection is used if the device later wants the server to resend lost packages. But with different addresses forked-daapd won't know who (which session) is requesting package resend. If there was some other id I could use that to match sessions, but I can't see what that would be.

**Comment by Iznohak** [comment] 2018-06-22 17:54
I know nothing about DAAP or AirPlay protocols so can't comment on that, but perhaps you could try to do a DNS reverse-lookup on A and B and if they resolve to the same hostname then they are in the same session. It's rather kludgy though.

**Comment by ejurgensen** [comment] 2018-08-18 20:41
I've had a ATV4 running for a while to see if I could reproduce this, but it has not appeared. However, my ATV4 never seems to accept ipv6 connections, even though it announces them, so forked-daapd ends up always using ipv4. So if the ipv6 connection was made perhaps I would be able to reproduce.

If anyone is able to reproduce this issue using non-beta tvOS please add a comment to this thread. Otherwise I will close this issue in a month or two.

**Comment by cdlenfert** [comment] 2018-08-30 18:41
I'm having the same issue on Airfoil Speakers Mac version 4.9.2. Turning off IPv6 works to get streaming going, but playback controls in Airfoil speakers no longer work. 

![image](https://user-images.githubusercontent.com/17277745/44872124-f0f95280-ac51-11e8-85ef-654fcd876ca9.png)

![image](https://user-images.githubusercontent.com/17277745/44871986-9c55d780-ac51-11e8-8f14-eaf27fd6ddac.png)

More details on the raspberrypi forum - https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=49928&p=1359596#p1359596

Airfoil Speakers can be downloaded for free here - https://rogueamoeba.com/legacy/

**Comment by ejurgensen** [comment] 2018-08-30 19:13
Despite the naming, these control requests have nothing to do with play/pause/next etc.:
`[2018-08-30 12:24:19] [  LOG]     raop: Control request from 10.1.10.201; not a RAOP client`

They are mainly used when the speaker wants to request packet resend (if a packet was lost). If forked-daapd shows this log message, it means that the request comes from an address that is not the one that the speaker announced via mdns. So please check the log line that says something like:
`[ INFO]     raop: Adding AirPlay device 123214431@name: password: 0, verification: 0, encrypt: 0, metadata: 1, type Other, address a.b.c.d:7000`

With ipv6 it is normal that a device uses different addresses when acting as server and as client, which is the cause of the above ipv6 issue. On ipv4 it is not normal, so your issue is probably something else.

The play/pause requests are an entirely different story, and not related to this issue.

**Comment by cdlenfert** [comment] 2018-08-31 16:38
I'll take a look at the log on the control request but can put it in a separate issue if it continues to be a problem after I get on the latest version of forked-daapd. 

As for the issue presented by @loudnate something very similar is happening on Airfoil Speakers (at least in our network) as he's experiencing with the ATV4. 

> Metadata appeared on screen, but audio was silent

Just wanted to make sure that part of it was clear in my addition to this issue thread.

**Comment by ejurgensen** [comment] 2018-09-07 19:39
To progress with this issue it would be helpful if any of you who are affected by it could send me a Wireshark dump of the traffic between forked-daapd and the ATV (when ipv6 is enabled and the silent playback starts). Since the ATV will have multiple ipv6 addresses it is important that you capture traffic to all these addresses, and you must also capture both tcp and udp. Stop the capture about 5 seconds into the silent playback, I don't need any more than that. Please send the capture to me espenjurgensen@gmail.com.

Also pinging @amaccuish here, since you mentioned you also have this problem.

**Comment by ejurgensen** [comment] 2018-09-21 19:49
While I am still unable to reproduce the original issue, my ATV4 did start exhibiting issues with ipv6 that have some similarity. The RECORD request to the ATV, which is the final step when starting playback, would hang for about 5 seconds, whereafter the ATV would return 500 Internal Server Error. During this step the device would normally try to establish a connection to forked-daapd's udp timing port, and I can only speculate that it is this connection attempt that fails and times out with ipv6. However, my traffic dump didn't reveal any actual connection attempts coming from the ATV.

I've added a workaround to forked-daapd so that if a device returns an error on ipv6, forked-daapd will be better at falling back to ipv4. Other than that I don't see there is much I can do, so I will close this issue.

If anyone comes across iTunes or Airfoil successfully starting an ipv6 session please put a notice here. I would love to have a dump of the traffic.

**Closed by ejurgensen** 2018-09-21 19:49 UTC
Labels: bug
