### ISSUE TITLE
Better support for rigelian

### ISSUE THREAD

**Issue by bendschs** [ejurgensen/forked-daapd#1158] opened 2021-01-08 13:43 UTC
https://apps.apple.com/de/app/rigelian/id1363775934

In general it works, would just be awesome to have a specific profile for forked-daapd written because loading of albums is very slow, also cover support is not really working. 

Supported MPD-Playertypes so far:

- classic mpd
- Volumio
- Bryston
- Rune Audio
- moOde

cheers
bendsch

**Comment by chme** [comment] 2021-01-09 10:17
Regelian does not seem to be open source. To get a forked-daapd profile in regelian you will have to ask the regelian developers, if they are interested in adding it.

The mpd protocol commands to retrieve local artwork are not implemented in forked-daapd. Some mpd clients supported fetching local artwork through http to the server that mpd runs on. This is supported by forked-daapd if you activate in forked-daapd.conf the property `http_port` in the `mpd` section. In regelian there would have to be a setting to set the http server for artwork. At least this is how it was implemented in MPDroid.

```
# MPD configuration (only have effect if MPD enabled - see README/INSTALL)
mpd {
...

	# HTTP port to listen for artwork requests (only supported by some MPD
	# clients and will need additional configuration in the MPD client to
	# work). Set to 0 to disable serving artwork over http.
#	http_port = 0

...
}
```

There is a chance that we can improve the performance for the album list. If you can provide a debug log that contains the requests made from regelian, I can take a look at what is taking so long and maybe there is an easy fix.

**Comment by bendschs** [comment] 2021-01-09 12:09
Thank you for the reply.

For the coverart i can set following values for the coverartfiles (see attachment). I already edited the http-port in the mpd section of forked-daapd.conf, i was not sure about the filenames of the cover though.

Attached as well i provide the console output while starting up and letting rigelian connect an load the albums of the mpd-server.

thank you for the help.

![Bildschirmfoto 2021-01-09 um 00 00 21](https://user-images.githubusercontent.com/17085451/104091161-eddbeb80-527b-11eb-9349-f61b2ea83543.png)
[rigelian.log](https://github.com/ejurgensen/forked-daapd/files/5790890/rigelian.log)

**Comment by chme** [comment] 2021-01-11 19:29
@bendschs What I meant is a forked-daapd.log in debug mode (forked-daapd logs the mpd commands it receives, which are necessary to analyze the problem. Can you provide a forked-daapd debug log?

The cover settings in regelian look like it should be possible to get artwork from forked-daapd. forked-daapd does not expect a "Cover Prefix" so setting this to empty could be worth a try. In a debug log you should also see the artwork requests being logged, this should give you further information why forked-daapd does not return an artwork for a file/album.

**Comment by bendschs** [comment] 2021-01-11 22:24
sorry, my bad. i attached a log (debug-level) from the point where the client connects to the point where it starts fetching albums (after that there are only album-fetching messages).
[forked.log](https://github.com/ejurgensen/forked-daapd/files/5798604/forked.log)

**Comment by chme** [comment] 2021-01-16 08:16
This command could be the cause for the performance issue:

```
[2021-01-11 23:19:17] [DEBUG]      mpd: MPD message: find modified-since "2020-07-15T22:19:50Z"
[2021-01-11 23:19:17] [ WARN]      mpd: Parameter 'modified-since' is not supported by forked-daapd and will be ignored
[2021-01-11 23:19:17] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0;'
[2021-01-11 23:19:17] [DEBUG]       db: Starting query 'SELECT f.* FROM files f WHERE f.disabled = 0  ORDER BY f.title_sort ;'
```

Due to forked-daapd not supporting the filter criteria it returns the all tracks from the library. I'll look into adding support for the `modified-since` filter criteria.

**Comment by chme** [comment] 2021-01-16 10:10
@bendschs I have merged support for the `modified-since` filter criteria to master (#1170). Would be great, if you could test it out and report if it works / improves the performance.

**Comment by bendschs** [comment] 2021-01-16 10:16
perfect, thank you so much!

**Comment by ejurgensen** [comment] 2021-02-11 13:24
Closing, no feedback

**Closed by ejurgensen** 2021-02-11 13:24 UTC
