### ISSUE TITLE
Database get's locked

### ISSUE THREAD

**Issue by atomicus** [ejurgensen/forked-daapd#88] opened 2015-01-18 12:57 UTC
Hi.

During initial scan of my library forked-dappd hang's on 
<code>
db: Waiting for database unlock
</code>
and does not go any further (I can wait couple of hours and still nothing).

It does not happen when I reinstall forked-daapd, first 2-3 scans are normal, but after couple of reboots this happens and makes it unusable until  next reinstall.

Any ideas of how to get rid of it?

Edit:
Running on raspbarrian.

**Comment by ejurgensen** [comment] 2015-01-18 14:21
I can't guess why that is, but you may be able to get rid of it if you move the database to /run (so it's in RAM). Obviously, you can't do that if if you don't have sufficient free memory, and you will lose it every time you reboot (unless you make some script handling that). If this method does not solve the problem, well then at least you know the problem isn't storage-related. If it does goes away, consider trying some other storage.

**Comment by atomicus** [comment] 2015-01-18 20:12
It was not storage related, I've turned on hihger log level and noticed that this in fact stalls on ffmpeg having some warnings while working on .flac file.
I've added .flac to ignore list (as I don't have much of them) and performed scan once more - with success.

I'll try check whats wrong with that and i'll get back to you.

**Comment by atomicus** [comment] 2015-01-18 22:15
Moving to /run didn't help
The only solution is to ignore .flac. The last things that can be seen are:
![image](https://cloud.githubusercontent.com/assets/188840/5794295/f0d0b762-9f67-11e4-92a3-4b2a7d0cfe58.png)

**Comment by ejurgensen** [comment] 2015-01-18 22:28
Ah, yes. The problem is that it takes so long to scan those flac's (more
than a minute each), that the cache update triggers during the scan. That's
not supposed to happen.

Temporary solutions:
- avoid the flac's, like you did
- disable the cache

Real solution:
- the next RPi version I release will have a limit on the scan time per
file, which should solve this and give you better scan times too (this
change is already here on GitHub but I assume you use the release for RPi?)
søn. 18. jan. 2015 kl. 23.15 skrev atomicus <notifications@github.com>:

**Comment by atomicus** [comment] 2015-01-18 22:32
I've used 2- one from apt, didn't worked
Second one I've build form source [https://github.com/ejurgensen/forked-daapd/commit/c2bc05cb16a57669a31dc077987768a0ec82e049], has the same problem.

I'll try to disable the cache and let's see how it will go.

**Comment by ejurgensen** [comment] 2015-01-18 22:36
Can you see in the log what the scan time is per flac?
søn. 18. jan. 2015 kl. 23.32 skrev atomicus <notifications@github.com>:

**Comment by atomicus** [comment] 2015-01-18 22:37
Nope,at least on -d 5.

**Comment by ejurgensen** [comment] 2015-01-18 22:43
Set the log level to debug and look in the log file (not console) and it
will say. If you have the problem with the Github version my diagnosis may
have been wrong.
søn. 18. jan. 2015 kl. 23.37 skrev atomicus <notifications@github.com>:

**Comment by atomicus** [comment] 2015-01-18 22:55
I see only ffmpeg logs, scan logs (bitrate, duration, streams), db logs (sql) - but can't find any scan time info.
What is the string for that? Like "scan time: XXs"?

**Comment by ejurgensen** [comment] 2015-01-18 22:59
There is no separate line, but every line has a time stamp. So you should
be able to see how long it takes that way.
søn. 18. jan. 2015 kl. 23.55 skrev atomicus <notifications@github.com>:

**Comment by atomicus** [comment] 2015-01-18 23:12
Haha, what I was thinking...:)

Thath migh be easier, last logs:
<code>
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: Probed with size=2048 and score=50
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=d8 avail_size_in_buf=86346
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 0 bytes (0 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=e0 avail_size_in_buf=86344
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 16 bytes (128 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=e2 avail_size_in_buf=86326
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 1283 bytes (10264 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=e1 avail_size_in_buf=85040
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 63 bytes (504 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=db avail_size_in_buf=84974
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: index=0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: qscale[0]: 1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 67 bytes (536 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=db avail_size_in_buf=84905
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: index=1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: qscale[1]: 2
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 67 bytes (536 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c0 avail_size_in_buf=84836
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: sof0: picture: 500x448
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component 0 2:2 id: 0 quant:0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component 1 1:1 id: 1 quant:1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component 2 1:1 id: 2 quant:1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: pix fmt id 22111100
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 17 bytes (136 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84817
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=0 index=0 nb_codes=12
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 31 bytes (248 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84784
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=1 index=0 nb_codes=251
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 181 bytes (1448 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84601
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=0 index=1 nb_codes=12
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 31 bytes (248 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84568
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=1 index=1 nb_codes=251
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 181 bytes (1448 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: escaping removed 742 bytes
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=da avail_size_in_buf=84385
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component: 0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component: 1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component: 2
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 83642 bytes (669136 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=d9 avail_size_in_buf=0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: mjpeg decode frame unused 0 bytes
[2015-01-19 00:06:03] [ WARN]   ffmpeg: max_analyze_duration reached
[2015-01-19 00:06:03] [DEBUG]     scan: File has 2 streams
[2015-01-19 00:06:03] [DEBUG]     scan: Found embedded artwork (stream 1)
[2015-01-19 00:06:03] [DEBUG]     scan: Duration 231920 ms, bitrate 782 kbps
[2015-01-19 00:06:03] [DEBUG]     scan: samplerate 44100, bps 16
[2015-01-19 00:06:03] [DEBUG]     scan: FLAC
[2015-01-19 00:06:03] [DEBUG]     scan: Picked up 2 tags from file metadata
[2015-01-19 00:06:03] [DEBUG]     scan: Picked up 2 tags with extra md_map
[2015-01-19 00:06:03] [DEBUG]     scan: Picked up 7 tags from file metadata
[2015-01-19 00:06:03] [DEBUG]     scan: Picked up 7 tags with generic md_map, 9 tags total
[2015-01-19 00:06:03] [DEBUG]       db: Running query 'INSERT INTO files (id, path, fname, title, artist, album, genre, comment, type, composer, orchestra, conductor, grouping, url, bitrate, samplerate, song_length, file_size, year, track, total_tracks, disc, total_discs, bpm, compilation, artwork, rating, play_count, seek, data_kind, item_kind, description, time_added, time_modified, time_played, db_timestamp, disabled, sample_count, codectype, idx, has_video, contentrating, bits_per_sample, album_artist, media_kind, tv_series_name, tv_episode_num_str, tv_network_name, tv_episode_sort, tv_season_num,  songartistid, songalbumid,  title_sort, artist_sort, album_sort, composer_sort, album_artist_sort )  VALUES (NULL, '/media/usb/Music/The Complete Pearl Jam/The Molo Sessions {Fan Club Release}/13 Intombi Ezilishumi.flac', '13 Intombi Ezilishumi.flac', TRIM('Intombi Ezilishumi'), TRIM('Eddie Vedder And The Walmer High School Chior'), TRIM('The Molo Sessions (Apple Lossless)'), TRIM('Pop'), TRIM(NULL), 'flac', TRIM(NULL), TRIM(NULL), TRIM(NULL), TRIM(NULL), NULL, 782, 44100, 231920, 22686850, 2004, 13, 15, 1, 1, 0, 0, 2, 0, 0, 0, 0, 2, 'FLAC audio file', 1421622363, 1332599812, 0, 1421622363, 0, 0, 'flac', 0, 0, 0, 16, TRIM('Eddie Vedder And The Walmer High School Chior'), 1, TRIM(NULL), TRIM(NULL), TRIM(NULL), 0, 0, daap_songalbumid(LOWER(TRIM('Eddie Vedder And The Walmer High School Chior')), ''), daap_songalbumid(LOWER(TRIM('Eddie Vedder And The Walmer High School Chior')), LOWER(TRIM('The Molo Sessions (Apple Lossless)'))),  TRIM('Intombi Ezilishumi'), TRIM('Eddie Vedder And The Walmer High School Chior'), TRIM('Molo Sessions (Apple Lossless)'), TRIM(NULL), TRIM('Eddie Vedder And The Walmer High School Chior'));'
[2015-01-19 00:06:03] [DEBUG]       db: Running query 'SELECT f.id, f.db_timestamp FROM files f WHERE f.path = '...';'
[2015-01-19 00:06:03] [DEBUG]       db: No results
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: Probed with size=2048 and score=50
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=d8 avail_size_in_buf=86346
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 0 bytes (0 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=e0 avail_size_in_buf=86344
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 16 bytes (128 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=e2 avail_size_in_buf=86326
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 1283 bytes (10264 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=e1 avail_size_in_buf=85040
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 63 bytes (504 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=db avail_size_in_buf=84974
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: index=0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: qscale[0]: 1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 67 bytes (536 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=db avail_size_in_buf=84905
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: index=1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: qscale[1]: 2
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 67 bytes (536 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c0 avail_size_in_buf=84836
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: sof0: picture: 500x448
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component 0 2:2 id: 0 quant:0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component 1 1:1 id: 1 quant:1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component 2 1:1 id: 2 quant:1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: pix fmt id 22111100
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 17 bytes (136 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84817
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=0 index=0 nb_codes=12
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 31 bytes (248 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84784
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=1 index=0 nb_codes=251
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 181 bytes (1448 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84601
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=0 index=1 nb_codes=12
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 31 bytes (248 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84568
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=1 index=1 nb_codes=251
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 181 bytes (1448 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: escaping removed 742 bytes
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=da avail_size_in_buf=84385
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component: 0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component: 1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component: 2
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 83642 bytes (669136 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=d9 avail_size_in_buf=0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: mjpeg decode frame unused 0 bytes
[2015-01-19 00:06:03] [ WARN]   ffmpeg: max_analyze_duration reached
[2015-01-19 00:06:03] [DEBUG]     scan: File has 2 streams
[2015-01-19 00:06:03] [DEBUG]     scan: Found embedded artwork (stream 1)
[2015-01-19 00:06:03] [DEBUG]     scan: Duration 111160 ms, bitrate 776 kbps
[2015-01-19 00:06:03] [DEBUG]     scan: samplerate 44100, bps 16
[2015-01-19 00:06:03] [DEBUG]     scan: FLAC
[2015-01-19 00:06:03] [DEBUG]     scan: Picked up 2 tags from file metadata
[2015-01-19 00:06:03] [DEBUG]     scan: Picked up 2 tags with extra md_map
[2015-01-19 00:06:03] [DEBUG]     scan: Picked up 7 tags from file metadata
[2015-01-19 00:06:03] [DEBUG]     scan: Picked up 7 tags with generic md_map, 9 tags total
[2015-01-19 00:06:03] [DEBUG]       db: Running query 'INSERT INTO files (id, path, fname, title, artist, album, genre, comment, type, composer, orchestra, conductor, grouping, url, bitrate, samplerate, song_length, file_size, year, track, total_tracks, disc, total_discs, bpm, compilation, artwork, rating, play_count, seek, data_kind, item_kind, description, time_added, time_modified, time_played, db_timestamp, disabled, sample_count, codectype, idx, has_video, contentrating, bits_per_sample, album_artist, media_kind, tv_series_name, tv_episode_num_str, tv_network_name, tv_episode_sort, tv_season_num,  songartistid, songalbumid,  title_sort, artist_sort, album_sort, composer_sort, album_artist_sort )  VALUES (NULL, '/media/usb/Music/The Complete Pearl Jam/The Molo Sessions {Fan Club Release}/14 Nkosi Sikelel'' iAfrika.flac', '14 Nkosi Sikelel'' iAfrika.flac', TRIM('Nkosi Sikelel'' iAfrika'), TRIM('Eddie Vedder And The Walmer High School Chior'), TRIM('The Molo Sessions (Apple Lossless)'), TRIM('Pop'), TRIM(NULL), 'flac', TRIM(NULL), TRIM(NULL), TRIM(NULL), TRIM(NULL), NULL, 776, 44100, 111160, 10783212, 2004, 14, 15, 1, 1, 0, 0, 2, 0, 0, 0, 0, 2, 'FLAC audio file', 1421622363, 1332626277, 0, 1421622363, 0, 0, 'flac', 0, 0, 0, 16, TRIM('Eddie Vedder And The Walmer High School Chior'), 1, TRIM(NULL), TRIM(NULL), TRIM(NULL), 0, 0, daap_songalbumid(LOWER(TRIM('Eddie Vedder And The Walmer High School Chior')), ''), daap_songalbumid(LOWER(TRIM('Eddie Vedder And The Walmer High School Chior')), LOWER(TRIM('The Molo Sessions (Apple Lossless)'))),  TRIM('Nkosi Sikelel'' iAfrika'), TRIM('Eddie Vedder And The Walmer High School Chior'), TRIM('Molo Sessions (Apple Lossless)'), TRIM(NULL), TRIM('Eddie Vedder And The Walmer High School Chior'));'
[2015-01-19 00:06:03] [DEBUG]       db: Running query 'SELECT f.id, f.db_timestamp FROM files f WHERE f.path = '...';'
[2015-01-19 00:06:03] [DEBUG]       db: No results
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: Probed with size=2048 and score=50
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=d8 avail_size_in_buf=86346
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 0 bytes (0 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=e0 avail_size_in_buf=86344
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 16 bytes (128 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=e2 avail_size_in_buf=86326
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 1283 bytes (10264 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=e1 avail_size_in_buf=85040
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 63 bytes (504 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=db avail_size_in_buf=84974
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: index=0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: qscale[0]: 1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 67 bytes (536 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=db avail_size_in_buf=84905
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: index=1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: qscale[1]: 2
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 67 bytes (536 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c0 avail_size_in_buf=84836
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: sof0: picture: 500x448
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component 0 2:2 id: 0 quant:0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component 1 1:1 id: 1 quant:1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component 2 1:1 id: 2 quant:1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: pix fmt id 22111100
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 17 bytes (136 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84817
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=0 index=0 nb_codes=12
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 31 bytes (248 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84784
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=1 index=0 nb_codes=251
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 181 bytes (1448 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84601
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=0 index=1 nb_codes=12
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 31 bytes (248 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=c4 avail_size_in_buf=84568
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: class=1 index=1 nb_codes=251
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 181 bytes (1448 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: escaping removed 742 bytes
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=da avail_size_in_buf=84385
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component: 0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component: 1
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: component: 2
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker parser used 83642 bytes (669136 bits)
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: marker=d9 avail_size_in_buf=0
[2015-01-19 00:06:03] [DEBUG]   ffmpeg: mjpeg decode frame unused 0 bytes
[2015-01-19 00:06:04] [ WARN]   ffmpeg: max_analyze_duration reached
[2015-01-19 00:06:04] [DEBUG]     scan: File has 2 streams
[2015-01-19 00:06:04] [DEBUG]     scan: Found embedded artwork (stream 1)
[2015-01-19 00:06:04] [DEBUG]     scan: Duration 167226 ms, bitrate 923 kbps
[2015-01-19 00:06:04] [DEBUG]     scan: samplerate 44100, bps 16
[2015-01-19 00:06:04] [DEBUG]     scan: FLAC
[2015-01-19 00:06:04] [DEBUG]     scan: Picked up 2 tags from file metadata
[2015-01-19 00:06:04] [DEBUG]     scan: Picked up 2 tags with extra md_map
[2015-01-19 00:06:04] [DEBUG]     scan: Picked up 7 tags from file metadata
[2015-01-19 00:06:04] [DEBUG]     scan: Picked up 7 tags with generic md_map, 9 tags total
[2015-01-19 00:06:04] [DEBUG]       db: Running query 'INSERT INTO files (id, path, fname, title, artist, album, genre, comment, type, composer, orchestra, conductor, grouping, url, bitrate, samplerate, song_length, file_size, year, track, total_tracks, disc, total_discs, bpm, compilation, artwork, rating, play_count, seek, data_kind, item_kind, description, time_added, time_modified, time_played, db_timestamp, disabled, sample_count, codectype, idx, has_video, contentrating, bits_per_sample, album_artist, media_kind, tv_series_name, tv_episode_num_str, tv_network_name, tv_episode_sort, tv_season_num,  songartistid, songalbumid,  title_sort, artist_sort, album_sort, composer_sort, album_artist_sort )  VALUES (NULL, '/media/usb/Music/The Complete Pearl Jam/The Molo Sessions {Fan Club Release}/15 Untitled.flac', '15 Untitled.flac', TRIM('Untitled'), TRIM('Eddie Vedder And The Walmer High School Chior'), TRIM('The Molo Sessions (Apple Lossless)'), TRIM('Pop'), TRIM(NULL), 'flac', TRIM(NULL), TRIM(NULL), TRIM(NULL), TRIM(NULL), NULL, 923, 44100, 167226, 19306187, 2004, 15, 15, 1, 1, 0, 0, 2, 0, 0, 0, 0, 2, 'FLAC audio file', 1421622364, 1332626925, 0, 1421622364, 0, 0, 'flac', 0, 0, 0, 16, TRIM('Eddie Vedder And The Walmer High School Chior'), 1, TRIM(NULL), TRIM(NULL), TRIM(NULL), 0, 0, daap_songalbumid(LOWER(TRIM('Eddie Vedder And The Walmer High School Chior')), ''), daap_songalbumid(LOWER(TRIM('Eddie Vedder And The Walmer High School Chior')), LOWER(TRIM('The Molo Sessions (Apple Lossless)'))),  TRIM('Untitled'), TRIM('Eddie Vedder And The Walmer High School Chior'), TRIM('Molo Sessions (Apple Lossless)'), TRIM(NULL), TRIM('Eddie Vedder And The Walmer High School Chior'));'
[2015-01-19 00:06:04] [DEBUG]       db: Running query 'INSERT INTO inotify (wd, cookie, path) VALUES (64, 0, '...');'
[2015-01-19 00:06:04] [DEBUG]     scan: Processing directory /... (flags = 0x1)
[2015-01-19 00:06:04] [DEBUG]       db: Running query 'SELECT f.id, f.db_timestamp FROM files f WHERE f.path = '...';'
[2015-01-19 00:06:04] [DEBUG]       db: No results
[2015-01-19 00:06:04] [DEBUG]   ffmpeg: Probed with size=2048 and score=50
[2015-01-19 00:06:04] [ WARN]   ffmpeg: max_analyze_duration reached
[2015-01-19 00:06:04] [DEBUG]     scan: File has 1 streams
[2015-01-19 00:06:04] [DEBUG]     scan: Duration 307906 ms, bitrate 1019 kbps
[2015-01-19 00:06:04] [DEBUG]     scan: samplerate 44100, bps 16
[2015-01-19 00:06:04] [DEBUG]     scan: FLAC
[2015-01-19 00:06:04] [DEBUG]     scan: Picked up 0 tags from file metadata
[2015-01-19 00:06:04] [DEBUG]     scan: Picked up 0 tags with extra md_map
[2015-01-19 00:06:04] [DEBUG]     scan: Picked up 7 tags from file metadata
[2015-01-19 00:06:04] [DEBUG]     scan: Picked up 7 tags with generic md_map, 7 tags total
[2015-01-19 00:06:04] [DEBUG]       db: Running query 'INSERT INTO files (id, path, fname, title, artist, album, genre, comment, type, composer, orchestra, conductor, grouping, url, bitrate, samplerate, song_length, file_size, year, track, total_tracks, disc, total_discs, bpm, compilation, artwork, rating, play_count, seek, data_kind, item_kind, description, time_added, time_modified, time_played, db_timestamp, disabled, sample_count, codectype, idx, has_video, contentrating, bits_per_sample, album_artist, media_kind, tv_series_name, tv_episode_num_str, tv_network_name, tv_episode_sort, tv_season_num,  songartistid, songalbumid,  title_sort, artist_sort, album_sort, composer_sort, album_artist_sort )  VALUES (NULL, '/media/usb/Music/The Complete Pearl Jam/Miscellaneous/Even Flow (Re-Recorded January 1992).flac', 'Even Flow (Re-Recorded January 1992).flac', TRIM('Even Flow (Re-Recorded January 1992)'), TRIM('Pearl Jam'), TRIM('Ten (Deluxe Edition)'), TRIM('Alternative'), TRIM(NULL), 'flac', TRIM(NULL), TRIM(NULL), TRIM(NULL), TRIM(NULL), NULL, 1019, 44100, 307906, 39223625, 2008, 8, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 2, 'FLAC audio file', 1421622364, 1331962545, 0, 1421622364, 0, 0, 'flac', 0, 0, 0, 16, TRIM('Pearl Jam'), 1, TRIM(NULL), TRIM(NULL), TRIM(NULL), 0, 0, daap_songalbumid(LOWER(TRIM('Pearl Jam')), ''), daap_songalbumid(LOWER(TRIM('Pearl Jam')), LOWER(TRIM('Ten (Deluxe Edition)'))),  TRIM('Even Flow (Re-Recorded January 01992)'), TRIM('Pearl Jam'), TRIM('Ten (Deluxe Edition)'), TRIM(NULL), TRIM('Pearl Jam'));'
[2015-01-19 00:06:04] [DEBUG]       db: Running query 'SELECT f.id, f.db_timestamp FROM files f WHERE f.path = '...';'
[2015-01-19 00:06:04] [DEBUG]       db: No results
[2015-01-19 00:06:07] [ WARN]   ffmpeg: Format detected only with low score of 25, misdetection possible!
</code>

**Comment by ejurgensen** [comment] 2015-01-19 07:58
So it froze after that? I don't see any errors, and the scan is fast enough. Maybe the last file (the one which is referenced in the last 'SELECT f.id, f.db_timestamp FROM files f WHERE f.path = ...') kills libav? Can you run avprobe on the file? (if you don't have avprobe installed: apt-get install libav-tools).

**Comment by atomicus** [comment] 2015-01-19 17:53
Yes, with no change for next 30 minutes.
avprobe ends exactly the same - hangs after "Format detected with...."

**Comment by ejurgensen** [comment] 2015-01-19 18:48
Can you try running "avprobe -probesize 64000 [yourfile]" and check if it hangs too? If it doesn't, then I think the problem can be fixed.

**Comment by atomicus** [comment] 2015-01-19 21:05
The same as above:/

**Comment by ejurgensen** [comment] 2015-01-20 11:02
Ok. I'm closing this, since this is apparently a libav bug, when it comes to that flac file. You could give ffmpeg a go, it might be solved there. But building it for RPi is probably a lot of work.

**Closed by ejurgensen** 2015-01-20 11:02 UTC

**Comment by atomicus** [comment] 2015-01-20 15:39
Yep, I agree, this is ffmpeg ralated, and probably only for newest version, as I had it all running before big rpi update. 

A lot of work, and time. I've heard it takes 3h on i7 to just compile....
Anyway, thanks for support.

**Comment by freultwah** [comment] 2015-01-20 18:24
ffmpeg 2.5.3 took 10 minutes to compile on a 2 GHz Core2Duo, so the estimate for i7 is off a couple of orders of magnitude. Indeed, the build process took less than two minutes on a four core 3 GHz Xeon. (I admit this is with almost everything disabled that forked-daapd does not need.)

**Comment by atomicus** [comment] 2015-01-20 18:26
Ok, so I'll give it a try this week.
