### ISSUE TITLE
discrete-pause dacp command (Sonos-Beam)

### ISSUE THREAD

**Issue by snizzleorg** [ejurgensen/forked-daapd#583] opened 2018-09-06 14:07 UTC
The Sonos Beam and probably other Sonos devices have a play/pause button

when connected via airplay(2) pressing the button logs the following:

```
[2018-09-03 18:17:49] [  LOG]     dacp: Unrecognized path '/ctrl-int/1/discrete-pause' in DACP request: '/ctrl-int/1/discrete-pause'
```

I'm not sure how exactly this should behave but I would expect the speaker to be turned on and off in forked-daapd (so rest of the speakers should keep playing). or alternatively the whole playback could pause/restart when pressed.

**Comment by cosinekitty** [comment] 2018-09-06 16:35
I have gone down this road in a different software project, adding support for Sonos One speakers. The problem I found is that the discrete-pause notification arrives a few seconds after the user presses the pause button on the speaker. There is also a `/ctrl-int/1/play` notification that arrives a few seconds after the user presses the button again, to resume music.

I tried to react to these notifications, but not only is the delay of a few seconds very annoying, I could not get it to work correctly. It seems like it is already too late and the Sonos One is confused or something. This wasn't clear.

Apple iTunes and iPhone seem to know instantly when this button is pressed, because they immediately react correctly to them: they toggle the pause/play icon on the display, and the music pauses/resumes, both without any perceptible delay. There must be some other signals than these `discrete-pause` and `play` notifications that arrive first to the sender.  I have studied Wireshark captures but so far I have not been able to spot what the signals are.  (Guess: it might be something subtle in the UDP timing traffic. Not sure.)

**Comment by ejurgensen** [comment] 2018-09-06 20:17
It is easy enough to map discrete-pause to pause/restart of playback, so I have done that in the discrete_pause1 branch if anyone wants to test it. I assume it will have the problems @cosinekitty mentions,  but if someone would check it would be good. And maybe laggy pausing is better than nothing at all?

It would also be possible to enable/disable speaker instead of playback pause/resume. I think it would be best to do whatever iTunes does - but I am not sure from the above what that is.

**Comment by cosinekitty** [comment] 2018-09-06 21:11
I just tried it here with my Sonos One speaker. The behavior is similar to what I saw before in my own software. In my test, I'm streaming to two different AirPlay speakers simultaneously: the Sonos One and an older Pioneer speaker. When I press pause on the Sonos One, it immediately mutes itself, but the music keeps playing on the Pioneer.  When I press pause again on the Sonos One, it blinks the white LED above the pause button a few times, but it stays silent.  In forked-daapd.log, each time I press the pause button, I see:

```
[2018-09-06 17:05:21] [  LOG]     dacp: No session-id specified in request
```

**Comment by cosinekitty** [comment] 2018-09-06 21:16
Correction: the behavior is a little more complicated.  Sometimes when I press the pause button, I see the LED above the pause button flash white slowly a few times, then red quickly a few times.  Sometimes it goes brighter white, then dimmer white. Sometimes I see the log message mentioned above, other times I don't. The behavior seems to be affected by how quickly I repeat pressing the button, and seems to alternate between two states (pause? resume?).

**Comment by ejurgensen** [comment] 2018-09-06 21:19
Make sure that you have set “trusted_networks” in forked-daapd.conf. Otherwise you get this message because the request is not from a trusted peer.

**Comment by cosinekitty** [comment] 2018-09-06 21:29
OK, I fixed trusted_networks and restarted the daemon. I'm still seeing those log messages, and the behavior is still the same.
```
[2018-09-06 17:27:43] [  LOG]     dacp: No session-id specified in request
[2018-09-06 17:28:01] [  LOG]     dacp: No session-id specified in request
```

**Comment by ejurgensen** [comment] 2018-09-06 21:30
Did you uncomment the setting? :-)

**Comment by cosinekitty** [comment] 2018-09-06 21:39
Yes, that is all I did to that line. It looks like this now:
```
        trusted_networks = { "localhost", "192.168", "fd" }
```
My home network IPv4 addresses are all of the form 192.168.1.XXX, so it made sense.

**Comment by cosinekitty** [comment] 2018-09-06 21:59
I have captured Wireshark traffic. I don't have time right now, but when I do, I will find the pause/play messages and post them here.

**Comment by snizzleorg** [comment] 2018-09-07 07:46
I used 
```
trusted_networks = { 'any'}
```
because I was suspecting that the connection was coming over ipv6 and therefore not in the trusted_networks range but I still get the same error.

**Comment by ejurgensen** [comment] 2018-09-07 07:49
What does the log say with the updated log statement? It should say "Denied request 'xxxx' from 'xxxx'" so you can see exactly what is getting denied, and from what address.

**Comment by cosinekitty** [comment] 2018-09-07 12:05
I just tried pressing pause on the Sonos One with the new debug print in forked-daapd. It is an IPv6 address:

```
[2018-09-07 08:04:14] [  LOG]     dacp: No session-id specified in request
[2018-09-07 08:04:14] [  LOG]     dacp: Denied request '/ctrl-int/1/discrete-pause' from '2602:306:375b:af80:7a28:caff:fec3:238c'
```

**Comment by cosinekitty** [comment] 2018-09-07 12:13
Here is the traffic from Wireshark. Pressing the button on the Sonos alternates between `discrete-pause` and `play` messages.

```
GET /ctrl-int/1/discrete-pause HTTP/1.1
Host: spearmint.local.
Active-Remote: 3401786252
User-Agent: AirPlay/366.0

```

```
GET /ctrl-int/1/play HTTP/1.1
Host: spearmint.local.
Active-Remote: 3401786252
User-Agent: AirPlay/366.0

```

**Comment by ejurgensen** [comment] 2018-09-07 14:49
I cannot reproduce "No session-id..." if I set trusted_networks to "any" and make the address check using "2602:306:375b:af80:7a28:caff:fec3:238c", and the code also looks ok to me.

I suppose those requests you caught with Wireshark don't bring us closer as to why the Sonos delays sending them?

**Comment by cosinekitty** [comment] 2018-09-07 15:50
I just tried with `trusted_networks = { "any" }` and now it works on Sonos One!  So I think the reason my software had problems was I wasn't expecting the command from a different IP address (v6 instead of v4). There is still a delay, but the Sonos One immediately mutes itself, so the user experience is OK.

**Comment by ejurgensen** [comment] 2018-09-07 19:43
Excellent. The mapping of discrete-pause is now in master, so I will close this issue.

**Closed by ejurgensen** 2018-09-07 19:43 UTC
