### ISSUE TITLE
Bad sound with Google home and Alsa

### ISSUE THREAD

**Issue by claudiosala80** [ejurgensen/forked-daapd#868] opened 2019-12-28 17:10 UTC
Hello

I configured to use the output of the raspberry and some google home mini.
If I play they one by one all is ok
If I play on standard output (alsa) and I add a google device, the sound stat to be broken all the the devices.

Is there something I need to tune? 

This is the messages in log

`[2019-12-28 14:00:58] [  LOG]    cache: Beginning DAAP cache update
[2019-12-28 14:00:58] [  LOG]    cache: DAAP cache updated
[2019-12-28 14:01:17] [  LOG]     cast: Offset is set to 2:100000000
[2019-12-28 14:01:17] [  LOG]   laudio: SNDRV_PCM_IOCTL_SYNC_PTR failed (-32)[2019-12-28 14:01:19] [  LOG]   player: Output delay detected (behind=233, max=150), resetting all outputs
[2019-12-28 14:01:20] [  LOG]     dacp: Unrecognized path '/ctrl-int/1/dmcp.device-busy=0' in DACP request: '/ctrl-int/1/dmcp.device-busy=0'
[2019-12-28 14:01:26] [  LOG]   player: Output delay detected (behind=166, max=150), resetting all outputs
[2019-12-28 14:01:26] [  LOG]   player: Bug! outputs_device_stop_delayed() called for a device that has no session
[2019-12-28 14:01:33] [  LOG]   player: Output delay detected (behind=184, max=150), resetting all outputs
[2019-12-28 14:01:43] [  LOG]   player: Output delay detected (behind=152, max=150), resetting all outputs
[2019-12-28 14:01:48] [  LOG]   player: Output delay detected (behind=172, max=150), resetting all outputs
[2019-12-28 14:01:51] [  LOG]     cast: Request 6 timed out, will run empty callback
`

Thanks a lot

**Comment by ejurgensen** [comment] 2019-12-28 19:58
Well that certainly is an impressive number of errors in a very short time. I don’t know the cause, so there is not much advice I can give you, except check if cpu maxes when this happens. When I have time I will also try to reproduce.

**Comment by claudiosala80** [comment] 2019-12-28 20:07
Hello

Thank you for your help.

This properties are not relevant for my issue?

*       sync_disable = false*

*       offset_ms = 0       adjust_period_seconds = 300*

Also, is there any example for exclude speakers? I am not able to find how
exclude one chromecast (one exclude, but other two ones be included) and
one airplay

Thanks a lot for your job

Regards
Claudio

Il giorno sab 28 dic 2019 alle ore 20:58 ejurgensen <
notifications@github.com> ha scritto:

**Comment by ejurgensen** [comment] 2019-12-28 20:15
I doubt offset_ms and adjust_period have any impact. With regard to sync_disable you can try changing it and see. 

Excluding is just:

chromecast “speakername”
{
  exclude = true
}

**Comment by claudiosala80** [comment] 2019-12-28 20:32
I will try with that option, thanks
Where is the place for exclude list? In the chromecast section?

Il giorno sab 28 dic 2019 alle ore 21:15 ejurgensen <
notifications@github.com> ha scritto:

**Comment by ejurgensen** [comment] 2019-12-30 19:39
I have now tried to reproduce using an RPi2 and a Google Home. I could not produce the issue. It looks like the first error is from ALSA, and last time I looked into SNDRV_PCM_IOCTL_SYNC_PTR is was a underrun. I don't know how that would be the case here, though. What version of forked-daapd are you using? And which RPi is it?

Perhaps you can set the log level to debug, and then attach the file (so don't paste a large log snippet here). Maybe it has some clues.

Re. the setting you probably already found it that it doesn't go into any section, as it is documented in the config file.

**Comment by claudiosala80** [comment] 2019-12-30 21:33
Hello

I am running version 27.0 on a Raspberry Pi 1 (I am waiting the 4, but I
have issue with shipping). I was suspecting that it is an hardware issue,
but I am not sure at 100%
For the log: do you want forked-daapd log, correct? I will send you

Thanks
Claudio

Il giorno lun 30 dic 2019 alle ore 20:39 ejurgensen <
notifications@github.com> ha scritto:

**Comment by claudiosala80** [comment] 2019-12-31 09:03
Hello

Here the logs

Regards
Claudio

Il giorno lun 30 dic 2019 alle ore 20:39 ejurgensen <
notifications@github.com> ha scritto:

**Comment by nk-gears** [comment] 2020-01-05 15:49
@claudio, can I know how to configure the Google home mini speaker in forked daapd.  I compiled with Chromecast but still not recognised. Is there any specific version I need to compile?

**Comment by claudiosala80** [comment] 2020-01-06 15:57
I didn't compiled: I installed last version and removed comment to the line
for chromecast and the mini as been detected (I have two mini)

Il giorno dom 5 gen 2020 alle ore 16:49 Nirmal <notifications@github.com>
ha scritto:

**Comment by ejurgensen** [comment] 2020-01-06 16:11
@nk-gears have you checked the log? You shouldn’t need to configure anything.

**Comment by nk-gears** [comment] 2020-01-07 03:11
My other chromecast devices are detected. Only the Google Home mini is not listed in the forked-daapd admin section

**Comment by ejurgensen** [comment] 2020-01-07 07:55
forked-daapd detects these devices via mdns announcements of the service "_googlecast._tcp", so you can try running "avahi-browse -a" to see if there is such an announcement from the Google Home mini.

BTW, this is a bit off topic, so please open a new issue when you have done the above.

**Comment by nk-gears** [comment] 2020-01-07 16:27
Thank you. I pulled from the source and compiled and i can see the home mini. May be i was using the old version. After re-install i lost the .conf file as i have not taken the backup. I will work on that.

**Comment by ejurgensen** [comment] 2020-01-10 23:14
I'm closing this issue, since I won't be spending time on it, the reason being that it is observed on an RPi1 which has an inadequate sound system anyway.

**Closed by ejurgensen** 2020-01-10 23:14 UTC
