### ISSUE TITLE
Spotify issue with artwork

### ISSUE THREAD

**Issue by aetolus** [ejurgensen/forked-daapd#329] opened 2017-01-03 01:01 UTC
Apologies if I'm not including enough detail - quite new to this! Please let me know any further information I can provide and I'll include it.

Running forked-daapd on a Raspberry Pi 3, Raspian Jessie. 

Did a fresh git pull and recompile of forked-daapd yesterday.

```
[2017-01-03 07:24:32] [  LOG]     main: Forked Media Server Version 24.2 taking off
[2017-01-03 07:24:32] [  LOG]     main: Built 2017-01-02 with: --enable-spotify --enable-chromecast --enable-mpd --with-alsa
```

Frequently when streaming from spotify, I encounter forked-daapd becoming unresponsive. 

This occurs both streaming via Airplay and via Chromecast. I haven't tested with local speakers. 

It isn't track or playlist specific, seems to be random. 

When it occurs, I get the below errors in the log:

```
[2017-01-03 06:00:49] [ INFO]   player: Opening 'spotify:track:0YxK4WEGk8rzdXxUdGjgS2' (id=489, item-id=13)
[2017-01-03 06:00:49] [ INFO]     cast: Connection to 'Chromecast-Audio-5d09249fb5a0fa009af4af2a3c61e289' established using TLS1.2
[2017-01-03 06:00:49] [ INFO]   player: Using selected Chromecast device 'Chromecast-Audio-5d09249fb5a0fa009af4af2a3c61e289'
[2017-01-03 06:00:52] [ WARN]  spotify: Getting artwork (spotify:track:0YxK4WEGk8rzdXxUdGjgS2) failed, Spotify error: Resource not yet loaded
[2017-01-03 06:00:52] [ WARN]  artwork: No artwork from Spotify for spotify:track:0YxK4WEGk8rzdXxUdGjgS2
[2017-01-03 06:00:52] [ INFO]     raop: Failed to retrieve artwork for file id 13; no artwork will be sent
[2017-01-03 06:00:53] [ INFO]   stream: Beginning mp3 streaming to ::ffff:10.0.0.8:54209
[2017-01-03 06:01:57] [ WARN]  spotify: Buffer full more than 300 times, pausing
[2017-01-03 06:02:57] [ WARN]  spotify: Buffer full more than 300 times, pausing
[2017-01-03 06:03:57] [ WARN]  spotify: Buffer full more than 300 times, pausing
[2017-01-03 06:04:58] [ WARN]  spotify: Buffer full more than 300 times, pausing

```

The last warning just keeps recurring after that, and the only solution is to kill forked-daapd and then to restart it. 

Any suggestions?

**Comment by aetolus** [comment] 2017-01-03 03:38
Although it doesn't provide much more info - below is a log excerpt with DEBUG enabled:

```
[2017-01-03 14:29:34] [DEBUG]     cast: RX 322 20c8554c-ec48-4f52-a8de-269876626fdd * urn:x-cast:com.google.cast.media {"type":"MEDIA_STATUS","status":[{"mediaSessionId":4,"playbackRate":1,"playerState":"PLAYING","currentTime":0.845117,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"currentItemId":4,"repeatMode":"REPEAT_OFF"}],"requestId":0}
[2017-01-03 14:29:35] [ WARN]  spotify: Getting artwork (spotify:track:4psRoaOLrAI1fiDWQHgiZX) failed, Spotify error: Resource not yet loaded
[2017-01-03 14:29:35] [ WARN]  artwork: No artwork from Spotify for spotify:track:4psRoaOLrAI1fiDWQHgiZX
[2017-01-03 14:29:35] [DEBUG]       db: End of query results
[2017-01-03 14:29:35] [DEBUG]  artwork: No artwork found for item 662
[2017-01-03 14:29:35] [ INFO]     raop: Failed to retrieve artwork for file id 13; no artwork will be sent
[2017-01-03 14:30:00] [DEBUG]      mpd: MPD message: outputs
[2017-01-03 14:30:37] [ WARN]  spotify: Buffer full more than 300 times, pausing
[2017-01-03 14:30:37] [DEBUG]  spotify: Nonblock pause request
[2017-01-03 14:31:37] [ WARN]  spotify: Buffer full more than 300 times, pausing
[2017-01-03 14:31:37] [DEBUG]  spotify: Nonblock pause request
```

**Comment by ejurgensen** [comment] 2017-01-03 12:37
I use Spotify frequently, and I also saw this recently. I think the root cause is instability on Spotify's side, but it is clear that forked-daapd is not responding very well to these instabilities. I have started working on a solution for that in the branch [inputs1](https://github.com/ejurgensen/forked-daapd/tree/inputs1), but it is going to require some more work before it can be merged. With these changes what should happen, when not enough audio data is arriving from Spotify, is that forked-daapd will just pause for a little while, waiting for more data.

**Comment by aetolus** [comment] 2017-01-03 22:00
Thank you! I'll wait for the fix

**Comment by ejurgensen** [comment] 2017-01-29 15:15
The fix for this issue should now be in the master branch here on Github. It should make forked-daapd better at handling unstable audio delivery from Spotify.

The fix comes together with a bunch of other changes to how input audio is handled. If you have the option, I would appreciate if you could give it try. It is not unlikely that a few new bugs made their way in, so hope you can help me find them.

**Comment by aetolus** [comment] 2017-01-30 02:23
Cheers, I'm updating it now. 

I'll have a play when I get home from work and definitely let you know if I find anything.

**Comment by ejurgensen** [comment] 2017-01-30 09:24
Noticed one bug which is that the Spotify audio buffer isn't being cleared when switching tracks. I expect to get that fixed later today.

**Comment by ejurgensen** [comment] 2017-01-30 22:12
The buffer flushing issue should be fixed now.

**Comment by aetolus** [comment] 2017-02-07 07:28
Sorry for the delay in getting to try this - I actually ended up having to rebuild my entire system, just got it back up and running today. 

Found another bug that seems to have made it's way in - I'll drop the log to debug and see if I can reproduce, but for now, here's the errror:

```
[2017-02-07 18:25:25] [  LOG]   stream: Error writing to streaming pipe: Resource temporarily unavailable
[2017-02-07 18:25:25] [  LOG]   stream: Error writing to streaming pipe: Resource temporarily unavailable
[2017-02-07 18:25:25] [  LOG]   stream: Error writing to streaming pipe: Resource temporarily unavailable
[2017-02-07 18:25:28] [FATAL]  spotify: pthread_mutex_lock(&artwork->mutex) failed at line 1314, error 22 (Invalid argument)
```

**Comment by ejurgensen** [comment] 2017-02-07 10:00
Can you elaborate on what you do to trigger this error? I would like to be able to reproduce.

**Comment by aetolus** [comment] 2017-02-07 10:13
Nothing out of the ordinary I don't think. Essentially:

Using MPC on raspbian.
Load a spotify playlist
mpc play, with random enabled, using a ChromeCast Audio as the speaker.

After a few songs - seems to vary from 2 to 7 in the couple of times it's occurred, it just happens.

**Comment by ejurgensen** [comment] 2017-02-07 22:32
Thanks. I see two errors, and the most serious one is of course the fatal condition reported in the last line. I couldn't reproduce that exactly, but I do have a guess about what could be causing it. I have tried to fix that with commit a183463 (is in the master branch). Let me know if it does anything for the above issue.

I will look at the pipe error later.

**Comment by aetolus** [comment] 2017-02-10 04:56
Thanks again, I've updated it now. 

Letting it run while I'm at work so I'll see what happens.

**Comment by ejurgensen** [comment] 2017-03-03 22:42
Closing, no feedback

**Closed by ejurgensen** 2017-03-03 22:42 UTC
Labels: bug
