### ISSUE TITLE
Random song plays instead of selected song with shuffle on

### ISSUE THREAD

**Issue by pcoultha** [ejurgensen/forked-daapd#366] opened 2017-03-11 16:25 UTC
The recent commit 62cb07 to always start shuffled playback with item 0 has broken song selection for me using the iOS Remote app when shuffle playback is turned on.

Expected behavior: When shuffled playback mode is active, and I tap a specific song in a playlist or album that specific song is played. After that song, playback continues with other random songs from the same album/playlist/etc.

Observed behavior: When shuffled playback mode is active, and I tap a specific song in a playlist or album, a randomly chosen song from that playlist/album plays instead.

It looks like this commit was introduced to avoid stating playback partway through the newly shuffled playlist and causing some songs to be "skipped." If that was in fact the goal, it may be necessary to add code to "force shuffle" to selected song into position 0.

**Comment by ejurgensen** [comment] 2017-03-11 18:33
Yes, I agree - and yes the goal of the commit was actually only to avoid having "Up next" being random length when in shuffle mode. @chme would you mind looking at this?

**Comment by chme** [comment] 2017-03-12 06:59
Before the persistent queue change shuffling the whole queue and starting with a random song was the desired behavior. This behavior was first introduced in #99.

I nearly never use shuffle, so i am fine either way. Has someone checked how iTunes handles this?

**Comment by ejurgensen** [comment] 2017-03-12 11:42
Good point. Made a quick test in iTunes. It seems it does not have the concept of permanent shuffle mode? When I start a track from album or artist view in Remote playback always starts in normal mode. If I then press the shuffle button, the entire album (except currently playing) gets shuffled and added to "Up next".

I don't know if it is worth the abandoning shuffle mode to copy this exactly? I think it would be fine to just play the selection and add the rest, shuffled, to the rest of the queue.

**Comment by ejurgensen** [comment] 2017-03-17 18:14
On the topic of shuffling, here is an interesting article from Spotify:
https://labs.spotify.com/2014/02/28/how-to-shuffle-songs/

**Comment by ejurgensen** [comment] 2017-03-31 05:43
@chme do you think you can look at this soon? I think the behavior to go for is to play the selection (if any), shuffle the rest and add to queue.

**Comment by chme** [comment] 2017-04-01 05:30
I looked into it, but have not found an unobtrusive way to change the current behavior. If you know how to make the change please go ahead (and i still do not think this is a bug, but the once agreed on behavior).

**Comment by ejurgensen** [comment] 2017-04-01 07:00
I agree that it is not a bug in that sense, but I think for the user the current behavior is not what you would expect. What is it that would obtrusive about the change?

**Comment by chme** [comment] 2017-04-01 08:04
Well, there are the different modes for queueedit_add (play, add, add next, random), then the different queries and quirks (with selected item and without). Then there is the shared function queueitem_add, that is also used from cue_play. Also shuffling is currently only supported on the queue and not on a list of media items. 

It is quite possible, that i am missing the obvious place to change the behavior for the play-mode with shuffle=on without risking to break other modes/commands. But currently, i think this would require refactoring of the queueedit_add and possibly the cue_play commands (with a high risk of breaking something along the way).

**Comment by ejurgensen** [comment] 2017-05-04 21:56
Closing this, fixed by @chme

**Closed by ejurgensen** 2017-05-04 21:56 UTC
Labels: bug
